// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_FRAME_UNSPECIFIED     FrameType = 0
	FrameType_FRAME_OPEN            FrameType = 1 // открыть TCP stream
	FrameType_FRAME_DATA            FrameType = 2
	FrameType_FRAME_CLOSE           FrameType = 3
	FrameType_FRAME_PING            FrameType = 4
	FrameType_FRAME_PONG            FrameType = 5
	FrameType_FRAME_BIND_REQUEST    FrameType = 10 // device -> relay
	FrameType_FRAME_BIND_OK         FrameType = 11 // relay -> device
	FrameType_FRAME_BIND_REJECTED   FrameType = 12 // relay -> device
	FrameType_FRAME_UNBIND_REQUEST  FrameType = 13 // device -> relay
	FrameType_FRAME_UNBIND_OK       FrameType = 14 // relay -> device
	FrameType_FRAME_UNBIND_REJECTED FrameType = 15 // relay -> device
	FrameType_FRAME_BIND_REVOKED    FrameType = 16 // relay -> device, active binding was removed server-side
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0:  "FRAME_UNSPECIFIED",
		1:  "FRAME_OPEN",
		2:  "FRAME_DATA",
		3:  "FRAME_CLOSE",
		4:  "FRAME_PING",
		5:  "FRAME_PONG",
		10: "FRAME_BIND_REQUEST",
		11: "FRAME_BIND_OK",
		12: "FRAME_BIND_REJECTED",
		13: "FRAME_UNBIND_REQUEST",
		14: "FRAME_UNBIND_OK",
		15: "FRAME_UNBIND_REJECTED",
		16: "FRAME_BIND_REVOKED",
	}
	FrameType_value = map[string]int32{
		"FRAME_UNSPECIFIED":     0,
		"FRAME_OPEN":            1,
		"FRAME_DATA":            2,
		"FRAME_CLOSE":           3,
		"FRAME_PING":            4,
		"FRAME_PONG":            5,
		"FRAME_BIND_REQUEST":    10,
		"FRAME_BIND_OK":         11,
		"FRAME_BIND_REJECTED":   12,
		"FRAME_UNBIND_REQUEST":  13,
		"FRAME_UNBIND_OK":       14,
		"FRAME_UNBIND_REJECTED": 15,
		"FRAME_BIND_REVOKED":    16,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FrameType              `protobuf:"varint,1,opt,name=type,proto3,enum=tunnel.FrameType" json:"type,omitempty"`
	StreamId      uint32                 `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetType() FrameType {
	if x != nil {
		return x.Type
	}
	return FrameType_FRAME_UNSPECIFIED
}

func (x *Frame) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tunnel.proto\x12\x06tunnel\"e\n" +
	"\x05Frame\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.tunnel.FrameTypeR\x04type\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\rR\bstreamId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*\x99\x02\n" +
	"\tFrameType\x12\x15\n" +
	"\x11FRAME_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FRAME_OPEN\x10\x01\x12\x0e\n" +
	"\n" +
	"FRAME_DATA\x10\x02\x12\x0f\n" +
	"\vFRAME_CLOSE\x10\x03\x12\x0e\n" +
	"\n" +
	"FRAME_PING\x10\x04\x12\x0e\n" +
	"\n" +
	"FRAME_PONG\x10\x05\x12\x16\n" +
	"\x12FRAME_BIND_REQUEST\x10\n" +
	"\x12\x11\n" +
	"\rFRAME_BIND_OK\x10\v\x12\x17\n" +
	"\x13FRAME_BIND_REJECTED\x10\f\x12\x18\n" +
	"\x14FRAME_UNBIND_REQUEST\x10\r\x12\x13\n" +
	"\x0fFRAME_UNBIND_OK\x10\x0e\x12\x19\n" +
	"\x15FRAME_UNBIND_REJECTED\x10\x0f\x12\x16\n" +
	"\x12FRAME_BIND_REVOKED\x10\x102;\n" +
	"\rTunnelService\x12*\n" +
	"\x06Tunnel\x12\r.tunnel.Frame\x1a\r.tunnel.Frame(\x010\x01BF\n" +
	"%com.projects.httpsserverapp.tunnel.v1P\x01Z\x1brelay/proto/tunnel;tunnelpbb\x06proto3"

var (
	file_proto_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_proto_rawDescData
}

var file_proto_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_tunnel_proto_goTypes = []any{
	(FrameType)(0), // 0: tunnel.FrameType
	(*Frame)(nil),  // 1: tunnel.Frame
}
var file_proto_tunnel_proto_depIdxs = []int32{
	0, // 0: tunnel.Frame.type:type_name -> tunnel.FrameType
	1, // 1: tunnel.TunnelService.Tunnel:input_type -> tunnel.Frame
	1, // 2: tunnel.TunnelService.Tunnel:output_type -> tunnel.Frame
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tunnel_proto_init() }
func file_proto_tunnel_proto_init() {
	if File_proto_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_proto_depIdxs,
		EnumInfos:         file_proto_tunnel_proto_enumTypes,
		MessageInfos:      file_proto_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_proto = out.File
	file_proto_tunnel_proto_goTypes = nil
	file_proto_tunnel_proto_depIdxs = nil
}
