// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainStatus int32

const (
	DomainStatus_DOMAIN_STATUS_UNSPECIFIED DomainStatus = 0
	DomainStatus_DOMAIN_STATUS_PENDING_DNS DomainStatus = 1
	DomainStatus_DOMAIN_STATUS_REGISTERED  DomainStatus = 2
	DomainStatus_DOMAIN_STATUS_DISABLED    DomainStatus = 3
	DomainStatus_DOMAIN_STATUS_REVOKED     DomainStatus = 4
)

// Enum value maps for DomainStatus.
var (
	DomainStatus_name = map[int32]string{
		0: "DOMAIN_STATUS_UNSPECIFIED",
		1: "DOMAIN_STATUS_PENDING_DNS",
		2: "DOMAIN_STATUS_REGISTERED",
		3: "DOMAIN_STATUS_DISABLED",
		4: "DOMAIN_STATUS_REVOKED",
	}
	DomainStatus_value = map[string]int32{
		"DOMAIN_STATUS_UNSPECIFIED": 0,
		"DOMAIN_STATUS_PENDING_DNS": 1,
		"DOMAIN_STATUS_REGISTERED":  2,
		"DOMAIN_STATUS_DISABLED":    3,
		"DOMAIN_STATUS_REVOKED":     4,
	}
)

func (x DomainStatus) Enum() *DomainStatus {
	p := new(DomainStatus)
	*p = x
	return p
}

func (x DomainStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_proto_enumTypes[0].Descriptor()
}

func (DomainStatus) Type() protoreflect.EnumType {
	return &file_proto_control_proto_enumTypes[0]
}

func (x DomainStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainStatus.Descriptor instead.
func (DomainStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

type DomainVerificationStatus int32

const (
	DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_UNSPECIFIED DomainVerificationStatus = 0
	DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_PENDING     DomainVerificationStatus = 1
	DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_VERIFIED    DomainVerificationStatus = 2
	DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_EXPIRED     DomainVerificationStatus = 3
)

// Enum value maps for DomainVerificationStatus.
var (
	DomainVerificationStatus_name = map[int32]string{
		0: "DOMAIN_VERIFICATION_STATUS_UNSPECIFIED",
		1: "DOMAIN_VERIFICATION_STATUS_PENDING",
		2: "DOMAIN_VERIFICATION_STATUS_VERIFIED",
		3: "DOMAIN_VERIFICATION_STATUS_EXPIRED",
	}
	DomainVerificationStatus_value = map[string]int32{
		"DOMAIN_VERIFICATION_STATUS_UNSPECIFIED": 0,
		"DOMAIN_VERIFICATION_STATUS_PENDING":     1,
		"DOMAIN_VERIFICATION_STATUS_VERIFIED":    2,
		"DOMAIN_VERIFICATION_STATUS_EXPIRED":     3,
	}
)

func (x DomainVerificationStatus) Enum() *DomainVerificationStatus {
	p := new(DomainVerificationStatus)
	*p = x
	return p
}

func (x DomainVerificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainVerificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_proto_enumTypes[1].Descriptor()
}

func (DomainVerificationStatus) Type() protoreflect.EnumType {
	return &file_proto_control_proto_enumTypes[1]
}

func (x DomainVerificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainVerificationStatus.Descriptor instead.
func (DomainVerificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

type ProofType int32

const (
	ProofType_PROOF_TYPE_UNSPECIFIED ProofType = 0
	ProofType_PROOF_TYPE_DNS_TXT     ProofType = 1
)

// Enum value maps for ProofType.
var (
	ProofType_name = map[int32]string{
		0: "PROOF_TYPE_UNSPECIFIED",
		1: "PROOF_TYPE_DNS_TXT",
	}
	ProofType_value = map[string]int32{
		"PROOF_TYPE_UNSPECIFIED": 0,
		"PROOF_TYPE_DNS_TXT":     1,
	}
)

func (x ProofType) Enum() *ProofType {
	p := new(ProofType)
	*p = x
	return p
}

func (x ProofType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProofType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_proto_enumTypes[2].Descriptor()
}

func (ProofType) Type() protoreflect.EnumType {
	return &file_proto_control_proto_enumTypes[2]
}

func (x ProofType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProofType.Descriptor instead.
func (ProofType) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

type DNSRecordType int32

const (
	DNSRecordType_DNS_RECORD_TYPE_UNSPECIFIED DNSRecordType = 0
	DNSRecordType_DNS_RECORD_TYPE_TXT         DNSRecordType = 1
	DNSRecordType_DNS_RECORD_TYPE_CNAME       DNSRecordType = 2
)

// Enum value maps for DNSRecordType.
var (
	DNSRecordType_name = map[int32]string{
		0: "DNS_RECORD_TYPE_UNSPECIFIED",
		1: "DNS_RECORD_TYPE_TXT",
		2: "DNS_RECORD_TYPE_CNAME",
	}
	DNSRecordType_value = map[string]int32{
		"DNS_RECORD_TYPE_UNSPECIFIED": 0,
		"DNS_RECORD_TYPE_TXT":         1,
		"DNS_RECORD_TYPE_CNAME":       2,
	}
)

func (x DNSRecordType) Enum() *DNSRecordType {
	p := new(DNSRecordType)
	*p = x
	return p
}

func (x DNSRecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DNSRecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_proto_enumTypes[3].Descriptor()
}

func (DNSRecordType) Type() protoreflect.EnumType {
	return &file_proto_control_proto_enumTypes[3]
}

func (x DNSRecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DNSRecordType.Descriptor instead.
func (DNSRecordType) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

type ControlErrorCode int32

const (
	ControlErrorCode_CONTROL_ERROR_CODE_UNSPECIFIED         ControlErrorCode = 0
	ControlErrorCode_CONTROL_ERROR_CODE_INVALID_DOMAIN      ControlErrorCode = 1
	ControlErrorCode_CONTROL_ERROR_CODE_DOMAIN_ALREADY_USED ControlErrorCode = 2
	ControlErrorCode_CONTROL_ERROR_CODE_DOMAIN_NOT_OWNED    ControlErrorCode = 3
	ControlErrorCode_CONTROL_ERROR_CODE_DOMAIN_DISABLED     ControlErrorCode = 4
	ControlErrorCode_CONTROL_ERROR_CODE_DEVICE_REVOKED      ControlErrorCode = 5
	ControlErrorCode_CONTROL_ERROR_CODE_DNS_PROOF_REQUIRED  ControlErrorCode = 6
	ControlErrorCode_CONTROL_ERROR_CODE_DNS_PROOF_INVALID   ControlErrorCode = 7
	ControlErrorCode_CONTROL_ERROR_CODE_DOMAIN_NOT_FOUND    ControlErrorCode = 9
	ControlErrorCode_CONTROL_ERROR_CODE_RATE_LIMITED        ControlErrorCode = 10
	ControlErrorCode_CONTROL_ERROR_CODE_INTERNAL            ControlErrorCode = 100
)

// Enum value maps for ControlErrorCode.
var (
	ControlErrorCode_name = map[int32]string{
		0:   "CONTROL_ERROR_CODE_UNSPECIFIED",
		1:   "CONTROL_ERROR_CODE_INVALID_DOMAIN",
		2:   "CONTROL_ERROR_CODE_DOMAIN_ALREADY_USED",
		3:   "CONTROL_ERROR_CODE_DOMAIN_NOT_OWNED",
		4:   "CONTROL_ERROR_CODE_DOMAIN_DISABLED",
		5:   "CONTROL_ERROR_CODE_DEVICE_REVOKED",
		6:   "CONTROL_ERROR_CODE_DNS_PROOF_REQUIRED",
		7:   "CONTROL_ERROR_CODE_DNS_PROOF_INVALID",
		9:   "CONTROL_ERROR_CODE_DOMAIN_NOT_FOUND",
		10:  "CONTROL_ERROR_CODE_RATE_LIMITED",
		100: "CONTROL_ERROR_CODE_INTERNAL",
	}
	ControlErrorCode_value = map[string]int32{
		"CONTROL_ERROR_CODE_UNSPECIFIED":         0,
		"CONTROL_ERROR_CODE_INVALID_DOMAIN":      1,
		"CONTROL_ERROR_CODE_DOMAIN_ALREADY_USED": 2,
		"CONTROL_ERROR_CODE_DOMAIN_NOT_OWNED":    3,
		"CONTROL_ERROR_CODE_DOMAIN_DISABLED":     4,
		"CONTROL_ERROR_CODE_DEVICE_REVOKED":      5,
		"CONTROL_ERROR_CODE_DNS_PROOF_REQUIRED":  6,
		"CONTROL_ERROR_CODE_DNS_PROOF_INVALID":   7,
		"CONTROL_ERROR_CODE_DOMAIN_NOT_FOUND":    9,
		"CONTROL_ERROR_CODE_RATE_LIMITED":        10,
		"CONTROL_ERROR_CODE_INTERNAL":            100,
	}
)

func (x ControlErrorCode) Enum() *ControlErrorCode {
	p := new(ControlErrorCode)
	*p = x
	return p
}

func (x ControlErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_proto_enumTypes[4].Descriptor()
}

func (ControlErrorCode) Type() protoreflect.EnumType {
	return &file_proto_control_proto_enumTypes[4]
}

func (x ControlErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlErrorCode.Descriptor instead.
func (ControlErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

type UpdateDeviceRegistrationRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion         uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ClientVersion           string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	SupportedFeatures       []string               `protobuf:"bytes,3,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	ClientReportedInstallId string                 `protobuf:"bytes,4,opt,name=client_reported_install_id,json=clientReportedInstallId,proto3" json:"client_reported_install_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateDeviceRegistrationRequest) Reset() {
	*x = UpdateDeviceRegistrationRequest{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRegistrationRequest) ProtoMessage() {}

func (x *UpdateDeviceRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRegistrationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDeviceRegistrationRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *UpdateDeviceRegistrationRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *UpdateDeviceRegistrationRequest) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *UpdateDeviceRegistrationRequest) GetClientReportedInstallId() string {
	if x != nil {
		return x.ClientReportedInstallId
	}
	return ""
}

type UpdateDeviceRegistrationResponse struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	Success                 bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message                 string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AcceptedProtocolVersion uint32                    `protobuf:"varint,3,opt,name=accepted_protocol_version,json=acceptedProtocolVersion,proto3" json:"accepted_protocol_version,omitempty"`
	ServerFeatures          []string                  `protobuf:"bytes,4,rep,name=server_features,json=serverFeatures,proto3" json:"server_features,omitempty"`
	Domains                 []*DomainInfo             `protobuf:"bytes,10,rep,name=domains,proto3" json:"domains,omitempty"`
	DomainVerifications     []*DomainVerificationInfo `protobuf:"bytes,11,rep,name=domain_verifications,json=domainVerifications,proto3" json:"domain_verifications,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateDeviceRegistrationResponse) Reset() {
	*x = UpdateDeviceRegistrationResponse{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRegistrationResponse) ProtoMessage() {}

func (x *UpdateDeviceRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRegistrationResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDeviceRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDeviceRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateDeviceRegistrationResponse) GetAcceptedProtocolVersion() uint32 {
	if x != nil {
		return x.AcceptedProtocolVersion
	}
	return 0
}

func (x *UpdateDeviceRegistrationResponse) GetServerFeatures() []string {
	if x != nil {
		return x.ServerFeatures
	}
	return nil
}

func (x *UpdateDeviceRegistrationResponse) GetDomains() []*DomainInfo {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *UpdateDeviceRegistrationResponse) GetDomainVerifications() []*DomainVerificationInfo {
	if x != nil {
		return x.DomainVerifications
	}
	return nil
}

type GetDeviceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceConfigRequest) Reset() {
	*x = GetDeviceConfigRequest{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigRequest) ProtoMessage() {}

func (x *GetDeviceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

type GetDeviceConfigResponse struct {
	state                             protoimpl.MessageState    `protogen:"open.v1"`
	MinSupportedTunnelProtocolVersion uint32                    `protobuf:"varint,1,opt,name=min_supported_tunnel_protocol_version,json=minSupportedTunnelProtocolVersion,proto3" json:"min_supported_tunnel_protocol_version,omitempty"`
	MaxSupportedTunnelProtocolVersion uint32                    `protobuf:"varint,2,opt,name=max_supported_tunnel_protocol_version,json=maxSupportedTunnelProtocolVersion,proto3" json:"max_supported_tunnel_protocol_version,omitempty"`
	PreferredTunnelProtocolVersion    uint32                    `protobuf:"varint,3,opt,name=preferred_tunnel_protocol_version,json=preferredTunnelProtocolVersion,proto3" json:"preferred_tunnel_protocol_version,omitempty"`
	RelayGrpcEndpoint                 string                    `protobuf:"bytes,10,opt,name=relay_grpc_endpoint,json=relayGrpcEndpoint,proto3" json:"relay_grpc_endpoint,omitempty"`
	PolicyMaxConcurrentStreams        uint32                    `protobuf:"varint,20,opt,name=policy_max_concurrent_streams,json=policyMaxConcurrentStreams,proto3" json:"policy_max_concurrent_streams,omitempty"`
	PolicyMaxFrameSizeBytes           uint32                    `protobuf:"varint,21,opt,name=policy_max_frame_size_bytes,json=policyMaxFrameSizeBytes,proto3" json:"policy_max_frame_size_bytes,omitempty"`
	DefaultPingIntervalSeconds        uint32                    `protobuf:"varint,22,opt,name=default_ping_interval_seconds,json=defaultPingIntervalSeconds,proto3" json:"default_ping_interval_seconds,omitempty"`
	ServerFeatures                    []string                  `protobuf:"bytes,30,rep,name=server_features,json=serverFeatures,proto3" json:"server_features,omitempty"`
	Domains                           []*DomainInfo             `protobuf:"bytes,40,rep,name=domains,proto3" json:"domains,omitempty"`
	DomainVerifications               []*DomainVerificationInfo `protobuf:"bytes,41,rep,name=domain_verifications,json=domainVerifications,proto3" json:"domain_verifications,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *GetDeviceConfigResponse) Reset() {
	*x = GetDeviceConfigResponse{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigResponse) ProtoMessage() {}

func (x *GetDeviceConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceConfigResponse) GetMinSupportedTunnelProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedTunnelProtocolVersion
	}
	return 0
}

func (x *GetDeviceConfigResponse) GetMaxSupportedTunnelProtocolVersion() uint32 {
	if x != nil {
		return x.MaxSupportedTunnelProtocolVersion
	}
	return 0
}

func (x *GetDeviceConfigResponse) GetPreferredTunnelProtocolVersion() uint32 {
	if x != nil {
		return x.PreferredTunnelProtocolVersion
	}
	return 0
}

func (x *GetDeviceConfigResponse) GetRelayGrpcEndpoint() string {
	if x != nil {
		return x.RelayGrpcEndpoint
	}
	return ""
}

func (x *GetDeviceConfigResponse) GetPolicyMaxConcurrentStreams() uint32 {
	if x != nil {
		return x.PolicyMaxConcurrentStreams
	}
	return 0
}

func (x *GetDeviceConfigResponse) GetPolicyMaxFrameSizeBytes() uint32 {
	if x != nil {
		return x.PolicyMaxFrameSizeBytes
	}
	return 0
}

func (x *GetDeviceConfigResponse) GetDefaultPingIntervalSeconds() uint32 {
	if x != nil {
		return x.DefaultPingIntervalSeconds
	}
	return 0
}

func (x *GetDeviceConfigResponse) GetServerFeatures() []string {
	if x != nil {
		return x.ServerFeatures
	}
	return nil
}

func (x *GetDeviceConfigResponse) GetDomains() []*DomainInfo {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *GetDeviceConfigResponse) GetDomainVerifications() []*DomainVerificationInfo {
	if x != nil {
		return x.DomainVerifications
	}
	return nil
}

type ListDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsRequest) Reset() {
	*x = ListDomainsRequest{}
	mi := &file_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsRequest) ProtoMessage() {}

func (x *ListDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

type ListDomainsResponse struct {
	state               protoimpl.MessageState    `protogen:"open.v1"`
	Domains             []*DomainInfo             `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	DomainVerifications []*DomainVerificationInfo `protobuf:"bytes,2,rep,name=domain_verifications,json=domainVerifications,proto3" json:"domain_verifications,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *ListDomainsResponse) GetDomains() []*DomainInfo {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *ListDomainsResponse) GetDomainVerifications() []*DomainVerificationInfo {
	if x != nil {
		return x.DomainVerifications
	}
	return nil
}

type UnregisterDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDomainRequest) Reset() {
	*x = UnregisterDomainRequest{}
	mi := &file_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDomainRequest) ProtoMessage() {}

func (x *UnregisterDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDomainRequest.ProtoReflect.Descriptor instead.
func (*UnregisterDomainRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{6}
}

func (x *UnregisterDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type UnregisterDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     ControlErrorCode       `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=control.v2.ControlErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDomainResponse) Reset() {
	*x = UnregisterDomainResponse{}
	mi := &file_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDomainResponse) ProtoMessage() {}

func (x *UnregisterDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDomainResponse.ProtoReflect.Descriptor instead.
func (*UnregisterDomainResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterDomainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterDomainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnregisterDomainResponse) GetErrorCode() ControlErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ControlErrorCode_CONTROL_ERROR_CODE_UNSPECIFIED
}

type RegisterDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Proof         *DomainOwnershipProof  `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDomainRequest) Reset() {
	*x = RegisterDomainRequest{}
	mi := &file_proto_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDomainRequest) ProtoMessage() {}

func (x *RegisterDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDomainRequest.ProtoReflect.Descriptor instead.
func (*RegisterDomainRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RegisterDomainRequest) GetProof() *DomainOwnershipProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type DomainOwnershipProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ProofType              `protobuf:"varint,1,opt,name=type,proto3,enum=control.v2.ProofType" json:"type,omitempty"`
	RecordName    string                 `protobuf:"bytes,2,opt,name=record_name,json=recordName,proto3" json:"record_name,omitempty"`
	RecordValue   string                 `protobuf:"bytes,3,opt,name=record_value,json=recordValue,proto3" json:"record_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainOwnershipProof) Reset() {
	*x = DomainOwnershipProof{}
	mi := &file_proto_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainOwnershipProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainOwnershipProof) ProtoMessage() {}

func (x *DomainOwnershipProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainOwnershipProof.ProtoReflect.Descriptor instead.
func (*DomainOwnershipProof) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{9}
}

func (x *DomainOwnershipProof) GetType() ProofType {
	if x != nil {
		return x.Type
	}
	return ProofType_PROOF_TYPE_UNSPECIFIED
}

func (x *DomainOwnershipProof) GetRecordName() string {
	if x != nil {
		return x.RecordName
	}
	return ""
}

func (x *DomainOwnershipProof) GetRecordValue() string {
	if x != nil {
		return x.RecordValue
	}
	return ""
}

type DomainRegistrationResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Success        bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode      ControlErrorCode        `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=control.v2.ControlErrorCode" json:"error_code,omitempty"`
	Domain         *DomainInfo             `protobuf:"bytes,10,opt,name=domain,proto3" json:"domain,omitempty"`
	DnsInstruction *DNSInstruction         `protobuf:"bytes,11,opt,name=dns_instruction,json=dnsInstruction,proto3" json:"dns_instruction,omitempty"`
	Verification   *DomainVerificationInfo `protobuf:"bytes,12,opt,name=verification,proto3" json:"verification,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DomainRegistrationResponse) Reset() {
	*x = DomainRegistrationResponse{}
	mi := &file_proto_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainRegistrationResponse) ProtoMessage() {}

func (x *DomainRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainRegistrationResponse.ProtoReflect.Descriptor instead.
func (*DomainRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{10}
}

func (x *DomainRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DomainRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DomainRegistrationResponse) GetErrorCode() ControlErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ControlErrorCode_CONTROL_ERROR_CODE_UNSPECIFIED
}

func (x *DomainRegistrationResponse) GetDomain() *DomainInfo {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *DomainRegistrationResponse) GetDnsInstruction() *DNSInstruction {
	if x != nil {
		return x.DnsInstruction
	}
	return nil
}

func (x *DomainRegistrationResponse) GetVerification() *DomainVerificationInfo {
	if x != nil {
		return x.Verification
	}
	return nil
}

type DNSInstruction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecordName      string                 `protobuf:"bytes,1,opt,name=record_name,json=recordName,proto3" json:"record_name,omitempty"`
	RecordType      DNSRecordType          `protobuf:"varint,2,opt,name=record_type,json=recordType,proto3,enum=control.v2.DNSRecordType" json:"record_type,omitempty"`
	RecordValue     string                 `protobuf:"bytes,3,opt,name=record_value,json=recordValue,proto3" json:"record_value,omitempty"`
	TtlSeconds      uint32                 `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Purpose         string                 `protobuf:"bytes,5,opt,name=purpose,proto3" json:"purpose,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,6,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DNSInstruction) Reset() {
	*x = DNSInstruction{}
	mi := &file_proto_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSInstruction) ProtoMessage() {}

func (x *DNSInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSInstruction.ProtoReflect.Descriptor instead.
func (*DNSInstruction) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{11}
}

func (x *DNSInstruction) GetRecordName() string {
	if x != nil {
		return x.RecordName
	}
	return ""
}

func (x *DNSInstruction) GetRecordType() DNSRecordType {
	if x != nil {
		return x.RecordType
	}
	return DNSRecordType_DNS_RECORD_TYPE_UNSPECIFIED
}

func (x *DNSInstruction) GetRecordValue() string {
	if x != nil {
		return x.RecordValue
	}
	return ""
}

func (x *DNSInstruction) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *DNSInstruction) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *DNSInstruction) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

type DomainInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Domain          string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Status          DomainStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=control.v2.DomainStatus" json:"status,omitempty"`
	ActiveBinding   bool                   `protobuf:"varint,4,opt,name=active_binding,json=activeBinding,proto3" json:"active_binding,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DomainInfo) Reset() {
	*x = DomainInfo{}
	mi := &file_proto_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainInfo) ProtoMessage() {}

func (x *DomainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainInfo.ProtoReflect.Descriptor instead.
func (*DomainInfo) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{12}
}

func (x *DomainInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainInfo) GetStatus() DomainStatus {
	if x != nil {
		return x.Status
	}
	return DomainStatus_DOMAIN_STATUS_UNSPECIFIED
}

func (x *DomainInfo) GetActiveBinding() bool {
	if x != nil {
		return x.ActiveBinding
	}
	return false
}

func (x *DomainInfo) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *DomainInfo) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

type DomainVerificationInfo struct {
	state                    protoimpl.MessageState   `protogen:"open.v1"`
	Domain                   string                   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Status                   DomainVerificationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=control.v2.DomainVerificationStatus" json:"status,omitempty"`
	DnsInstruction           *DNSInstruction          `protobuf:"bytes,3,opt,name=dns_instruction,json=dnsInstruction,proto3" json:"dns_instruction,omitempty"`
	VerificationAttempts     uint32                   `protobuf:"varint,4,opt,name=verification_attempts,json=verificationAttempts,proto3" json:"verification_attempts,omitempty"`
	NextVerificationAtUnixMs int64                    `protobuf:"varint,5,opt,name=next_verification_at_unix_ms,json=nextVerificationAtUnixMs,proto3" json:"next_verification_at_unix_ms,omitempty"`
	LastVerificationAtUnixMs int64                    `protobuf:"varint,6,opt,name=last_verification_at_unix_ms,json=lastVerificationAtUnixMs,proto3" json:"last_verification_at_unix_ms,omitempty"`
	LastError                string                   `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	VerifiedAtUnixMs         int64                    `protobuf:"varint,8,opt,name=verified_at_unix_ms,json=verifiedAtUnixMs,proto3" json:"verified_at_unix_ms,omitempty"`
	CanRequestNewChallenge   bool                     `protobuf:"varint,9,opt,name=can_request_new_challenge,json=canRequestNewChallenge,proto3" json:"can_request_new_challenge,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DomainVerificationInfo) Reset() {
	*x = DomainVerificationInfo{}
	mi := &file_proto_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainVerificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainVerificationInfo) ProtoMessage() {}

func (x *DomainVerificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainVerificationInfo.ProtoReflect.Descriptor instead.
func (*DomainVerificationInfo) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{13}
}

func (x *DomainVerificationInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainVerificationInfo) GetStatus() DomainVerificationStatus {
	if x != nil {
		return x.Status
	}
	return DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_UNSPECIFIED
}

func (x *DomainVerificationInfo) GetDnsInstruction() *DNSInstruction {
	if x != nil {
		return x.DnsInstruction
	}
	return nil
}

func (x *DomainVerificationInfo) GetVerificationAttempts() uint32 {
	if x != nil {
		return x.VerificationAttempts
	}
	return 0
}

func (x *DomainVerificationInfo) GetNextVerificationAtUnixMs() int64 {
	if x != nil {
		return x.NextVerificationAtUnixMs
	}
	return 0
}

func (x *DomainVerificationInfo) GetLastVerificationAtUnixMs() int64 {
	if x != nil {
		return x.LastVerificationAtUnixMs
	}
	return 0
}

func (x *DomainVerificationInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *DomainVerificationInfo) GetVerifiedAtUnixMs() int64 {
	if x != nil {
		return x.VerifiedAtUnixMs
	}
	return 0
}

func (x *DomainVerificationInfo) GetCanRequestNewChallenge() bool {
	if x != nil {
		return x.CanRequestNewChallenge
	}
	return false
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\n" +
	"control.v2\"\xf2\x01\n" +
	"\x1fUpdateDeviceRegistrationRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12-\n" +
	"\x12supported_features\x18\x03 \x03(\tR\x11supportedFeatures\x12;\n" +
	"\x1aclient_reported_install_id\x18\x04 \x01(\tR\x17clientReportedInstallIdJ\x04\b\x05\x10\x06R\vdevice_info\"\xc4\x02\n" +
	" UpdateDeviceRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x19accepted_protocol_version\x18\x03 \x01(\rR\x17acceptedProtocolVersion\x12'\n" +
	"\x0fserver_features\x18\x04 \x03(\tR\x0eserverFeatures\x120\n" +
	"\adomains\x18\n" +
	" \x03(\v2\x16.control.v2.DomainInfoR\adomains\x12U\n" +
	"\x14domain_verifications\x18\v \x03(\v2\".control.v2.DomainVerificationInfoR\x13domainVerifications\"\x18\n" +
	"\x16GetDeviceConfigRequest\"\xf8\x05\n" +
	"\x17GetDeviceConfigResponse\x12P\n" +
	"%min_supported_tunnel_protocol_version\x18\x01 \x01(\rR!minSupportedTunnelProtocolVersion\x12P\n" +
	"%max_supported_tunnel_protocol_version\x18\x02 \x01(\rR!maxSupportedTunnelProtocolVersion\x12I\n" +
	"!preferred_tunnel_protocol_version\x18\x03 \x01(\rR\x1epreferredTunnelProtocolVersion\x12.\n" +
	"\x13relay_grpc_endpoint\x18\n" +
	" \x01(\tR\x11relayGrpcEndpoint\x12A\n" +
	"\x1dpolicy_max_concurrent_streams\x18\x14 \x01(\rR\x1apolicyMaxConcurrentStreams\x12<\n" +
	"\x1bpolicy_max_frame_size_bytes\x18\x15 \x01(\rR\x17policyMaxFrameSizeBytes\x12A\n" +
	"\x1ddefault_ping_interval_seconds\x18\x16 \x01(\rR\x1adefaultPingIntervalSeconds\x12'\n" +
	"\x0fserver_features\x18\x1e \x03(\tR\x0eserverFeatures\x120\n" +
	"\adomains\x18( \x03(\v2\x16.control.v2.DomainInfoR\adomains\x12U\n" +
	"\x14domain_verifications\x18) \x03(\v2\".control.v2.DomainVerificationInfoR\x13domainVerificationsJ\x04\b\v\x10\fJ\x04\b2\x103J\x04\b3\x104R\x0eadmin_endpointR\x0fmanaged_zone_idR\x15managed_domain_suffix\"\x14\n" +
	"\x12ListDomainsRequest\"\x9e\x01\n" +
	"\x13ListDomainsResponse\x120\n" +
	"\adomains\x18\x01 \x03(\v2\x16.control.v2.DomainInfoR\adomains\x12U\n" +
	"\x14domain_verifications\x18\x02 \x03(\v2\".control.v2.DomainVerificationInfoR\x13domainVerifications\"1\n" +
	"\x17UnregisterDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\x8b\x01\n" +
	"\x18UnregisterDomainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x1c.control.v2.ControlErrorCodeR\terrorCode\"g\n" +
	"\x15RegisterDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x126\n" +
	"\x05proof\x18\x02 \x01(\v2 .control.v2.DomainOwnershipProofR\x05proof\"\x85\x01\n" +
	"\x14DomainOwnershipProof\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.control.v2.ProofTypeR\x04type\x12\x1f\n" +
	"\vrecord_name\x18\x02 \x01(\tR\n" +
	"recordName\x12!\n" +
	"\frecord_value\x18\x03 \x01(\tR\vrecordValue\"\xca\x02\n" +
	"\x1aDomainRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x1c.control.v2.ControlErrorCodeR\terrorCode\x12.\n" +
	"\x06domain\x18\n" +
	" \x01(\v2\x16.control.v2.DomainInfoR\x06domain\x12C\n" +
	"\x0fdns_instruction\x18\v \x01(\v2\x1a.control.v2.DNSInstructionR\x0ednsInstruction\x12F\n" +
	"\fverification\x18\f \x01(\v2\".control.v2.DomainVerificationInfoR\fverification\"\xf8\x01\n" +
	"\x0eDNSInstruction\x12\x1f\n" +
	"\vrecord_name\x18\x01 \x01(\tR\n" +
	"recordName\x12:\n" +
	"\vrecord_type\x18\x02 \x01(\x0e2\x19.control.v2.DNSRecordTypeR\n" +
	"recordType\x12!\n" +
	"\frecord_value\x18\x03 \x01(\tR\vrecordValue\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\rR\n" +
	"ttlSeconds\x12\x18\n" +
	"\apurpose\x18\x05 \x01(\tR\apurpose\x12+\n" +
	"\x12expires_at_unix_ms\x18\x06 \x01(\x03R\x0fexpiresAtUnixMs\"\xf1\x01\n" +
	"\n" +
	"DomainInfo\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.control.v2.DomainStatusR\x06status\x12%\n" +
	"\x0eactive_binding\x18\x04 \x01(\bR\ractiveBinding\x12+\n" +
	"\x12created_at_unix_ms\x18\x05 \x01(\x03R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\x06 \x01(\x03R\x0fupdatedAtUnixMsJ\x04\b\x03\x10\x04R\x12relay_managed_zone\"\xf1\x03\n" +
	"\x16DomainVerificationInfo\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.control.v2.DomainVerificationStatusR\x06status\x12C\n" +
	"\x0fdns_instruction\x18\x03 \x01(\v2\x1a.control.v2.DNSInstructionR\x0ednsInstruction\x123\n" +
	"\x15verification_attempts\x18\x04 \x01(\rR\x14verificationAttempts\x12>\n" +
	"\x1cnext_verification_at_unix_ms\x18\x05 \x01(\x03R\x18nextVerificationAtUnixMs\x12>\n" +
	"\x1clast_verification_at_unix_ms\x18\x06 \x01(\x03R\x18lastVerificationAtUnixMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12-\n" +
	"\x13verified_at_unix_ms\x18\b \x01(\x03R\x10verifiedAtUnixMs\x129\n" +
	"\x19can_request_new_challenge\x18\t \x01(\bR\x16canRequestNewChallenge*\xa1\x01\n" +
	"\fDomainStatus\x12\x1d\n" +
	"\x19DOMAIN_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DOMAIN_STATUS_PENDING_DNS\x10\x01\x12\x1c\n" +
	"\x18DOMAIN_STATUS_REGISTERED\x10\x02\x12\x1a\n" +
	"\x16DOMAIN_STATUS_DISABLED\x10\x03\x12\x19\n" +
	"\x15DOMAIN_STATUS_REVOKED\x10\x04*\xbf\x01\n" +
	"\x18DomainVerificationStatus\x12*\n" +
	"&DOMAIN_VERIFICATION_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"DOMAIN_VERIFICATION_STATUS_PENDING\x10\x01\x12'\n" +
	"#DOMAIN_VERIFICATION_STATUS_VERIFIED\x10\x02\x12&\n" +
	"\"DOMAIN_VERIFICATION_STATUS_EXPIRED\x10\x03*?\n" +
	"\tProofType\x12\x1a\n" +
	"\x16PROOF_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROOF_TYPE_DNS_TXT\x10\x01*d\n" +
	"\rDNSRecordType\x12\x1f\n" +
	"\x1bDNS_RECORD_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DNS_RECORD_TYPE_TXT\x10\x01\x12\x19\n" +
	"\x15DNS_RECORD_TYPE_CNAME\x10\x02*\xca\x04\n" +
	"\x10ControlErrorCode\x12\"\n" +
	"\x1eCONTROL_ERROR_CODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!CONTROL_ERROR_CODE_INVALID_DOMAIN\x10\x01\x12*\n" +
	"&CONTROL_ERROR_CODE_DOMAIN_ALREADY_USED\x10\x02\x12'\n" +
	"#CONTROL_ERROR_CODE_DOMAIN_NOT_OWNED\x10\x03\x12&\n" +
	"\"CONTROL_ERROR_CODE_DOMAIN_DISABLED\x10\x04\x12%\n" +
	"!CONTROL_ERROR_CODE_DEVICE_REVOKED\x10\x05\x12)\n" +
	"%CONTROL_ERROR_CODE_DNS_PROOF_REQUIRED\x10\x06\x12(\n" +
	"$CONTROL_ERROR_CODE_DNS_PROOF_INVALID\x10\a\x12'\n" +
	"#CONTROL_ERROR_CODE_DOMAIN_NOT_FOUND\x10\t\x12#\n" +
	"\x1fCONTROL_ERROR_CODE_RATE_LIMITED\x10\n" +
	"\x12\x1f\n" +
	"\x1bCONTROL_ERROR_CODE_INTERNAL\x10d\"\x04\b\b\x10\b\"\x04\b\v\x10\v\"\x04\b\f\x10\f**CONTROL_ERROR_CODE_SUBDOMAIN_NOT_AVAILABLE*#CONTROL_ERROR_CODE_ZONE_NOT_ALLOWED* CONTROL_ERROR_CODE_INVALID_LABEL2\xef\x03\n" +
	"\x0eControlService\x12u\n" +
	"\x18UpdateDeviceRegistration\x12+.control.v2.UpdateDeviceRegistrationRequest\x1a,.control.v2.UpdateDeviceRegistrationResponse\x12Z\n" +
	"\x0fGetDeviceConfig\x12\".control.v2.GetDeviceConfigRequest\x1a#.control.v2.GetDeviceConfigResponse\x12N\n" +
	"\vListDomains\x12\x1e.control.v2.ListDomainsRequest\x1a\x1f.control.v2.ListDomainsResponse\x12]\n" +
	"\x10UnregisterDomain\x12#.control.v2.UnregisterDomainRequest\x1a$.control.v2.UnregisterDomainResponse\x12[\n" +
	"\x0eRegisterDomain\x12!.control.v2.RegisterDomainRequest\x1a&.control.v2.DomainRegistrationResponseBL\n" +
	"&com.projects.httpsserverapp.control.v2P\x01Z relay/proto/control/v2;controlpbb\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_control_proto_goTypes = []any{
	(DomainStatus)(0),                        // 0: control.v2.DomainStatus
	(DomainVerificationStatus)(0),            // 1: control.v2.DomainVerificationStatus
	(ProofType)(0),                           // 2: control.v2.ProofType
	(DNSRecordType)(0),                       // 3: control.v2.DNSRecordType
	(ControlErrorCode)(0),                    // 4: control.v2.ControlErrorCode
	(*UpdateDeviceRegistrationRequest)(nil),  // 5: control.v2.UpdateDeviceRegistrationRequest
	(*UpdateDeviceRegistrationResponse)(nil), // 6: control.v2.UpdateDeviceRegistrationResponse
	(*GetDeviceConfigRequest)(nil),           // 7: control.v2.GetDeviceConfigRequest
	(*GetDeviceConfigResponse)(nil),          // 8: control.v2.GetDeviceConfigResponse
	(*ListDomainsRequest)(nil),               // 9: control.v2.ListDomainsRequest
	(*ListDomainsResponse)(nil),              // 10: control.v2.ListDomainsResponse
	(*UnregisterDomainRequest)(nil),          // 11: control.v2.UnregisterDomainRequest
	(*UnregisterDomainResponse)(nil),         // 12: control.v2.UnregisterDomainResponse
	(*RegisterDomainRequest)(nil),            // 13: control.v2.RegisterDomainRequest
	(*DomainOwnershipProof)(nil),             // 14: control.v2.DomainOwnershipProof
	(*DomainRegistrationResponse)(nil),       // 15: control.v2.DomainRegistrationResponse
	(*DNSInstruction)(nil),                   // 16: control.v2.DNSInstruction
	(*DomainInfo)(nil),                       // 17: control.v2.DomainInfo
	(*DomainVerificationInfo)(nil),           // 18: control.v2.DomainVerificationInfo
}
var file_proto_control_proto_depIdxs = []int32{
	17, // 0: control.v2.UpdateDeviceRegistrationResponse.domains:type_name -> control.v2.DomainInfo
	18, // 1: control.v2.UpdateDeviceRegistrationResponse.domain_verifications:type_name -> control.v2.DomainVerificationInfo
	17, // 2: control.v2.GetDeviceConfigResponse.domains:type_name -> control.v2.DomainInfo
	18, // 3: control.v2.GetDeviceConfigResponse.domain_verifications:type_name -> control.v2.DomainVerificationInfo
	17, // 4: control.v2.ListDomainsResponse.domains:type_name -> control.v2.DomainInfo
	18, // 5: control.v2.ListDomainsResponse.domain_verifications:type_name -> control.v2.DomainVerificationInfo
	4,  // 6: control.v2.UnregisterDomainResponse.error_code:type_name -> control.v2.ControlErrorCode
	14, // 7: control.v2.RegisterDomainRequest.proof:type_name -> control.v2.DomainOwnershipProof
	2,  // 8: control.v2.DomainOwnershipProof.type:type_name -> control.v2.ProofType
	4,  // 9: control.v2.DomainRegistrationResponse.error_code:type_name -> control.v2.ControlErrorCode
	17, // 10: control.v2.DomainRegistrationResponse.domain:type_name -> control.v2.DomainInfo
	16, // 11: control.v2.DomainRegistrationResponse.dns_instruction:type_name -> control.v2.DNSInstruction
	18, // 12: control.v2.DomainRegistrationResponse.verification:type_name -> control.v2.DomainVerificationInfo
	3,  // 13: control.v2.DNSInstruction.record_type:type_name -> control.v2.DNSRecordType
	0,  // 14: control.v2.DomainInfo.status:type_name -> control.v2.DomainStatus
	1,  // 15: control.v2.DomainVerificationInfo.status:type_name -> control.v2.DomainVerificationStatus
	16, // 16: control.v2.DomainVerificationInfo.dns_instruction:type_name -> control.v2.DNSInstruction
	5,  // 17: control.v2.ControlService.UpdateDeviceRegistration:input_type -> control.v2.UpdateDeviceRegistrationRequest
	7,  // 18: control.v2.ControlService.GetDeviceConfig:input_type -> control.v2.GetDeviceConfigRequest
	9,  // 19: control.v2.ControlService.ListDomains:input_type -> control.v2.ListDomainsRequest
	11, // 20: control.v2.ControlService.UnregisterDomain:input_type -> control.v2.UnregisterDomainRequest
	13, // 21: control.v2.ControlService.RegisterDomain:input_type -> control.v2.RegisterDomainRequest
	6,  // 22: control.v2.ControlService.UpdateDeviceRegistration:output_type -> control.v2.UpdateDeviceRegistrationResponse
	8,  // 23: control.v2.ControlService.GetDeviceConfig:output_type -> control.v2.GetDeviceConfigResponse
	10, // 24: control.v2.ControlService.ListDomains:output_type -> control.v2.ListDomainsResponse
	12, // 25: control.v2.ControlService.UnregisterDomain:output_type -> control.v2.UnregisterDomainResponse
	15, // 26: control.v2.ControlService.RegisterDomain:output_type -> control.v2.DomainRegistrationResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		EnumInfos:         file_proto_control_proto_enumTypes,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
