// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServeMode int32

const (
	ServeMode_SERVE_MODE_UNSPECIFIED       ServeMode = 0
	ServeMode_SERVE_MODE_HTTPS_PASSTHROUGH ServeMode = 1
)

// Enum value maps for ServeMode.
var (
	ServeMode_name = map[int32]string{
		0: "SERVE_MODE_UNSPECIFIED",
		1: "SERVE_MODE_HTTPS_PASSTHROUGH",
	}
	ServeMode_value = map[string]int32{
		"SERVE_MODE_UNSPECIFIED":       0,
		"SERVE_MODE_HTTPS_PASSTHROUGH": 1,
	}
)

func (x ServeMode) Enum() *ServeMode {
	p := new(ServeMode)
	*p = x
	return p
}

func (x ServeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[0].Descriptor()
}

func (ServeMode) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[0]
}

func (x ServeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServeMode.Descriptor instead.
func (ServeMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

type DomainStatus int32

const (
	DomainStatus_DOMAIN_STATUS_UNSPECIFIED DomainStatus = 0
	DomainStatus_DOMAIN_STATUS_PENDING_DNS DomainStatus = 1
	DomainStatus_DOMAIN_STATUS_REGISTERED  DomainStatus = 2
	DomainStatus_DOMAIN_STATUS_DISABLED    DomainStatus = 3
	DomainStatus_DOMAIN_STATUS_REVOKED     DomainStatus = 4
)

// Enum value maps for DomainStatus.
var (
	DomainStatus_name = map[int32]string{
		0: "DOMAIN_STATUS_UNSPECIFIED",
		1: "DOMAIN_STATUS_PENDING_DNS",
		2: "DOMAIN_STATUS_REGISTERED",
		3: "DOMAIN_STATUS_DISABLED",
		4: "DOMAIN_STATUS_REVOKED",
	}
	DomainStatus_value = map[string]int32{
		"DOMAIN_STATUS_UNSPECIFIED": 0,
		"DOMAIN_STATUS_PENDING_DNS": 1,
		"DOMAIN_STATUS_REGISTERED":  2,
		"DOMAIN_STATUS_DISABLED":    3,
		"DOMAIN_STATUS_REVOKED":     4,
	}
)

func (x DomainStatus) Enum() *DomainStatus {
	p := new(DomainStatus)
	*p = x
	return p
}

func (x DomainStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[1].Descriptor()
}

func (DomainStatus) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[1]
}

func (x DomainStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainStatus.Descriptor instead.
func (DomainStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

type DomainVerificationStatus int32

const (
	DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_UNSPECIFIED DomainVerificationStatus = 0
	DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_PENDING     DomainVerificationStatus = 1
	DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_VERIFIED    DomainVerificationStatus = 2
	DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_EXPIRED     DomainVerificationStatus = 3
)

var (
	DomainVerificationStatus_name = map[int32]string{
		0: "DOMAIN_VERIFICATION_STATUS_UNSPECIFIED",
		1: "DOMAIN_VERIFICATION_STATUS_PENDING",
		2: "DOMAIN_VERIFICATION_STATUS_VERIFIED",
		3: "DOMAIN_VERIFICATION_STATUS_EXPIRED",
	}
	DomainVerificationStatus_value = map[string]int32{
		"DOMAIN_VERIFICATION_STATUS_UNSPECIFIED": 0,
		"DOMAIN_VERIFICATION_STATUS_PENDING":     1,
		"DOMAIN_VERIFICATION_STATUS_VERIFIED":    2,
		"DOMAIN_VERIFICATION_STATUS_EXPIRED":     3,
	}
)

func (x DomainVerificationStatus) Enum() *DomainVerificationStatus {
	p := new(DomainVerificationStatus)
	*p = x
	return p
}

func (x DomainVerificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainVerificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[2].Descriptor()
}

func (DomainVerificationStatus) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[2]
}

func (x DomainVerificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (DomainVerificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

type CloseReason int32

const (
	CloseReason_CLOSE_REASON_UNSPECIFIED   CloseReason = 0
	CloseReason_CLOSE_REASON_NORMAL        CloseReason = 1
	CloseReason_CLOSE_REASON_REMOTE_CLOSED CloseReason = 2
	CloseReason_CLOSE_REASON_LOCAL_CLOSED  CloseReason = 3
	CloseReason_CLOSE_REASON_IDLE_TIMEOUT  CloseReason = 4
	CloseReason_CLOSE_REASON_POLICY_LIMIT  CloseReason = 5
	CloseReason_CLOSE_REASON_ERROR         CloseReason = 6
)

var (
	CloseReason_name = map[int32]string{
		0: "CLOSE_REASON_UNSPECIFIED",
		1: "CLOSE_REASON_NORMAL",
		2: "CLOSE_REASON_REMOTE_CLOSED",
		3: "CLOSE_REASON_LOCAL_CLOSED",
		4: "CLOSE_REASON_IDLE_TIMEOUT",
		5: "CLOSE_REASON_POLICY_LIMIT",
		6: "CLOSE_REASON_ERROR",
	}
	CloseReason_value = map[string]int32{
		"CLOSE_REASON_UNSPECIFIED":   0,
		"CLOSE_REASON_NORMAL":        1,
		"CLOSE_REASON_REMOTE_CLOSED": 2,
		"CLOSE_REASON_LOCAL_CLOSED":  3,
		"CLOSE_REASON_IDLE_TIMEOUT":  4,
		"CLOSE_REASON_POLICY_LIMIT":  5,
		"CLOSE_REASON_ERROR":         6,
	}
)

func (x CloseReason) Enum() *CloseReason {
	p := new(CloseReason)
	*p = x
	return p
}

func (x CloseReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloseReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[3].Descriptor()
}

func (CloseReason) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[3]
}

func (x CloseReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloseReason.Descriptor instead.
func (CloseReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

type DisconnectReason int32

const (
	DisconnectReason_DISCONNECT_REASON_UNSPECIFIED       DisconnectReason = 0
	DisconnectReason_DISCONNECT_REASON_NETWORK_LOST      DisconnectReason = 1
	DisconnectReason_DISCONNECT_REASON_AUTH_EXPIRED      DisconnectReason = 2
	DisconnectReason_DISCONNECT_REASON_SERVER_RESTART    DisconnectReason = 3
	DisconnectReason_DISCONNECT_REASON_PROTOCOL_MISMATCH DisconnectReason = 4
	DisconnectReason_DISCONNECT_REASON_DEVICE_REVOKED    DisconnectReason = 5
	DisconnectReason_DISCONNECT_REASON_SERVER_OVERLOADED DisconnectReason = 6
	DisconnectReason_DISCONNECT_REASON_IDLE_TIMEOUT      DisconnectReason = 7
)

var (
	DisconnectReason_name = map[int32]string{
		0: "DISCONNECT_REASON_UNSPECIFIED",
		1: "DISCONNECT_REASON_NETWORK_LOST",
		2: "DISCONNECT_REASON_AUTH_EXPIRED",
		3: "DISCONNECT_REASON_SERVER_RESTART",
		4: "DISCONNECT_REASON_PROTOCOL_MISMATCH",
		5: "DISCONNECT_REASON_DEVICE_REVOKED",
		6: "DISCONNECT_REASON_SERVER_OVERLOADED",
		7: "DISCONNECT_REASON_IDLE_TIMEOUT",
	}
	DisconnectReason_value = map[string]int32{
		"DISCONNECT_REASON_UNSPECIFIED":       0,
		"DISCONNECT_REASON_NETWORK_LOST":      1,
		"DISCONNECT_REASON_AUTH_EXPIRED":      2,
		"DISCONNECT_REASON_SERVER_RESTART":    3,
		"DISCONNECT_REASON_PROTOCOL_MISMATCH": 4,
		"DISCONNECT_REASON_DEVICE_REVOKED":    5,
		"DISCONNECT_REASON_SERVER_OVERLOADED": 6,
		"DISCONNECT_REASON_IDLE_TIMEOUT":      7,
	}
)

func (x DisconnectReason) Enum() *DisconnectReason {
	p := new(DisconnectReason)
	*p = x
	return p
}

func (x DisconnectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[4].Descriptor()
}

func (DisconnectReason) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[4]
}

func (x DisconnectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectReason.Descriptor instead.
func (DisconnectReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

type DomainRevokeReason int32

const (
	DomainRevokeReason_DOMAIN_REVOKE_REASON_UNSPECIFIED         DomainRevokeReason = 0
	DomainRevokeReason_DOMAIN_REVOKE_REASON_DNS_INVALID         DomainRevokeReason = 1
	DomainRevokeReason_DOMAIN_REVOKE_REASON_ADMIN_ACTION        DomainRevokeReason = 2
	DomainRevokeReason_DOMAIN_REVOKE_REASON_DOMAIN_UNREGISTERED DomainRevokeReason = 4
)

// Enum value maps for DomainRevokeReason.
var (
	DomainRevokeReason_name = map[int32]string{
		0: "DOMAIN_REVOKE_REASON_UNSPECIFIED",
		1: "DOMAIN_REVOKE_REASON_DNS_INVALID",
		2: "DOMAIN_REVOKE_REASON_ADMIN_ACTION",
		4: "DOMAIN_REVOKE_REASON_DOMAIN_UNREGISTERED",
	}
	DomainRevokeReason_value = map[string]int32{
		"DOMAIN_REVOKE_REASON_UNSPECIFIED":         0,
		"DOMAIN_REVOKE_REASON_DNS_INVALID":         1,
		"DOMAIN_REVOKE_REASON_ADMIN_ACTION":        2,
		"DOMAIN_REVOKE_REASON_DOMAIN_UNREGISTERED": 4,
	}
)

func (x DomainRevokeReason) Enum() *DomainRevokeReason {
	p := new(DomainRevokeReason)
	*p = x
	return p
}

func (x DomainRevokeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainRevokeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[5].Descriptor()
}

func (DomainRevokeReason) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[5]
}

func (x DomainRevokeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainRevokeReason.Descriptor instead.
func (DomainRevokeReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

type TunnelErrorCode int32

const (
	TunnelErrorCode_TUNNEL_ERROR_CODE_UNSPECIFIED                  TunnelErrorCode = 0
	TunnelErrorCode_TUNNEL_ERROR_CODE_INVALID_FRAME                TunnelErrorCode = 1
	TunnelErrorCode_TUNNEL_ERROR_CODE_PROTOCOL_VERSION_UNSUPPORTED TunnelErrorCode = 2
	TunnelErrorCode_TUNNEL_ERROR_CODE_AUTHENTICATION_REQUIRED      TunnelErrorCode = 3
	TunnelErrorCode_TUNNEL_ERROR_CODE_DEVICE_REVOKED               TunnelErrorCode = 4
	TunnelErrorCode_TUNNEL_ERROR_CODE_INVALID_DOMAIN               TunnelErrorCode = 5
	TunnelErrorCode_TUNNEL_ERROR_CODE_DOMAIN_NOT_REGISTERED        TunnelErrorCode = 6
	TunnelErrorCode_TUNNEL_ERROR_CODE_DOMAIN_NOT_OWNED             TunnelErrorCode = 7
	TunnelErrorCode_TUNNEL_ERROR_CODE_DOMAIN_DISABLED              TunnelErrorCode = 8
	TunnelErrorCode_TUNNEL_ERROR_CODE_DOMAIN_ALREADY_BOUND         TunnelErrorCode = 9
	TunnelErrorCode_TUNNEL_ERROR_CODE_STREAM_NOT_FOUND             TunnelErrorCode = 10
	TunnelErrorCode_TUNNEL_ERROR_CODE_STREAM_LIMIT_EXCEEDED        TunnelErrorCode = 11
	TunnelErrorCode_TUNNEL_ERROR_CODE_FRAME_TOO_LARGE              TunnelErrorCode = 12
	TunnelErrorCode_TUNNEL_ERROR_CODE_SERVER_UNDER_PRESSURE        TunnelErrorCode = 13
	TunnelErrorCode_TUNNEL_ERROR_CODE_INTERNAL                     TunnelErrorCode = 100
)

// Enum value maps for TunnelErrorCode.
var (
	TunnelErrorCode_name = map[int32]string{
		0:   "TUNNEL_ERROR_CODE_UNSPECIFIED",
		1:   "TUNNEL_ERROR_CODE_INVALID_FRAME",
		2:   "TUNNEL_ERROR_CODE_PROTOCOL_VERSION_UNSUPPORTED",
		3:   "TUNNEL_ERROR_CODE_AUTHENTICATION_REQUIRED",
		4:   "TUNNEL_ERROR_CODE_DEVICE_REVOKED",
		5:   "TUNNEL_ERROR_CODE_INVALID_DOMAIN",
		6:   "TUNNEL_ERROR_CODE_DOMAIN_NOT_REGISTERED",
		7:   "TUNNEL_ERROR_CODE_DOMAIN_NOT_OWNED",
		8:   "TUNNEL_ERROR_CODE_DOMAIN_DISABLED",
		9:   "TUNNEL_ERROR_CODE_DOMAIN_ALREADY_BOUND",
		10:  "TUNNEL_ERROR_CODE_STREAM_NOT_FOUND",
		11:  "TUNNEL_ERROR_CODE_STREAM_LIMIT_EXCEEDED",
		12:  "TUNNEL_ERROR_CODE_FRAME_TOO_LARGE",
		13:  "TUNNEL_ERROR_CODE_SERVER_UNDER_PRESSURE",
		100: "TUNNEL_ERROR_CODE_INTERNAL",
	}
	TunnelErrorCode_value = map[string]int32{
		"TUNNEL_ERROR_CODE_UNSPECIFIED":                  0,
		"TUNNEL_ERROR_CODE_INVALID_FRAME":                1,
		"TUNNEL_ERROR_CODE_PROTOCOL_VERSION_UNSUPPORTED": 2,
		"TUNNEL_ERROR_CODE_AUTHENTICATION_REQUIRED":      3,
		"TUNNEL_ERROR_CODE_DEVICE_REVOKED":               4,
		"TUNNEL_ERROR_CODE_INVALID_DOMAIN":               5,
		"TUNNEL_ERROR_CODE_DOMAIN_NOT_REGISTERED":        6,
		"TUNNEL_ERROR_CODE_DOMAIN_NOT_OWNED":             7,
		"TUNNEL_ERROR_CODE_DOMAIN_DISABLED":              8,
		"TUNNEL_ERROR_CODE_DOMAIN_ALREADY_BOUND":         9,
		"TUNNEL_ERROR_CODE_STREAM_NOT_FOUND":             10,
		"TUNNEL_ERROR_CODE_STREAM_LIMIT_EXCEEDED":        11,
		"TUNNEL_ERROR_CODE_FRAME_TOO_LARGE":              12,
		"TUNNEL_ERROR_CODE_SERVER_UNDER_PRESSURE":        13,
		"TUNNEL_ERROR_CODE_INTERNAL":                     100,
	}
)

func (x TunnelErrorCode) Enum() *TunnelErrorCode {
	p := new(TunnelErrorCode)
	*p = x
	return p
}

func (x TunnelErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[6].Descriptor()
}

func (TunnelErrorCode) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[6]
}

func (x TunnelErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelErrorCode.Descriptor instead.
func (TunnelErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

type Frame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StreamId  uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_StreamData
	//	*Frame_StreamOpen
	//	*Frame_StreamClose
	//	*Frame_StreamReset
	//	*Frame_StreamOpenResult
	//	*Frame_Hello
	//	*Frame_Welcome
	//	*Frame_Ping
	//	*Frame_Pong
	//	*Frame_Goaway
	//	*Frame_Error
	//	*Frame_BindRequest
	//	*Frame_BindResult
	//	*Frame_UnbindRequest
	//	*Frame_UnbindResult
	//	*Frame_DomainSync
	//	*Frame_DomainRevoked
	//	*Frame_DomainVerificationUpdate
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Frame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetStreamData() []byte {
	if x != nil {
		if x, ok := x.Body.(*Frame_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

func (x *Frame) GetStreamOpen() *StreamOpen {
	if x != nil {
		if x, ok := x.Body.(*Frame_StreamOpen); ok {
			return x.StreamOpen
		}
	}
	return nil
}

func (x *Frame) GetStreamClose() *StreamClose {
	if x != nil {
		if x, ok := x.Body.(*Frame_StreamClose); ok {
			return x.StreamClose
		}
	}
	return nil
}

func (x *Frame) GetStreamReset() *StreamReset {
	if x != nil {
		if x, ok := x.Body.(*Frame_StreamReset); ok {
			return x.StreamReset
		}
	}
	return nil
}

func (x *Frame) GetStreamOpenResult() *StreamOpenResult {
	if x != nil {
		if x, ok := x.Body.(*Frame_StreamOpenResult); ok {
			return x.StreamOpenResult
		}
	}
	return nil
}

func (x *Frame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Frame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Frame) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*Frame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *Frame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*Frame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Frame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*Frame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Frame) GetGoaway() *GoAway {
	if x != nil {
		if x, ok := x.Body.(*Frame_Goaway); ok {
			return x.Goaway
		}
	}
	return nil
}

func (x *Frame) GetError() *TunnelError {
	if x != nil {
		if x, ok := x.Body.(*Frame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Frame) GetBindRequest() *BindRequest {
	if x != nil {
		if x, ok := x.Body.(*Frame_BindRequest); ok {
			return x.BindRequest
		}
	}
	return nil
}

func (x *Frame) GetBindResult() *BindResult {
	if x != nil {
		if x, ok := x.Body.(*Frame_BindResult); ok {
			return x.BindResult
		}
	}
	return nil
}

func (x *Frame) GetUnbindRequest() *UnbindRequest {
	if x != nil {
		if x, ok := x.Body.(*Frame_UnbindRequest); ok {
			return x.UnbindRequest
		}
	}
	return nil
}

func (x *Frame) GetUnbindResult() *UnbindResult {
	if x != nil {
		if x, ok := x.Body.(*Frame_UnbindResult); ok {
			return x.UnbindResult
		}
	}
	return nil
}

func (x *Frame) GetDomainSync() *DomainSync {
	if x != nil {
		if x, ok := x.Body.(*Frame_DomainSync); ok {
			return x.DomainSync
		}
	}
	return nil
}

func (x *Frame) GetDomainRevoked() *DomainRevoked {
	if x != nil {
		if x, ok := x.Body.(*Frame_DomainRevoked); ok {
			return x.DomainRevoked
		}
	}
	return nil
}

func (x *Frame) GetDomainVerificationUpdate() *DomainVerificationUpdate {
	if x != nil {
		if x, ok := x.Body.(*Frame_DomainVerificationUpdate); ok {
			return x.DomainVerificationUpdate
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_StreamData struct {
	StreamData []byte `protobuf:"bytes,10,opt,name=stream_data,json=streamData,proto3,oneof"`
}

type Frame_StreamOpen struct {
	StreamOpen *StreamOpen `protobuf:"bytes,11,opt,name=stream_open,json=streamOpen,proto3,oneof"`
}

type Frame_StreamClose struct {
	StreamClose *StreamClose `protobuf:"bytes,12,opt,name=stream_close,json=streamClose,proto3,oneof"`
}

type Frame_StreamReset struct {
	StreamReset *StreamReset `protobuf:"bytes,13,opt,name=stream_reset,json=streamReset,proto3,oneof"`
}

type Frame_StreamOpenResult struct {
	StreamOpenResult *StreamOpenResult `protobuf:"bytes,14,opt,name=stream_open_result,json=streamOpenResult,proto3,oneof"`
}

type Frame_Hello struct {
	Hello *Hello `protobuf:"bytes,20,opt,name=hello,proto3,oneof"`
}

type Frame_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,21,opt,name=welcome,proto3,oneof"`
}

type Frame_Ping struct {
	Ping *Ping `protobuf:"bytes,22,opt,name=ping,proto3,oneof"`
}

type Frame_Pong struct {
	Pong *Pong `protobuf:"bytes,23,opt,name=pong,proto3,oneof"`
}

type Frame_Goaway struct {
	Goaway *GoAway `protobuf:"bytes,24,opt,name=goaway,proto3,oneof"`
}

type Frame_Error struct {
	Error *TunnelError `protobuf:"bytes,25,opt,name=error,proto3,oneof"`
}

type Frame_BindRequest struct {
	BindRequest *BindRequest `protobuf:"bytes,30,opt,name=bind_request,json=bindRequest,proto3,oneof"`
}

type Frame_BindResult struct {
	BindResult *BindResult `protobuf:"bytes,31,opt,name=bind_result,json=bindResult,proto3,oneof"`
}

type Frame_UnbindRequest struct {
	UnbindRequest *UnbindRequest `protobuf:"bytes,32,opt,name=unbind_request,json=unbindRequest,proto3,oneof"`
}

type Frame_UnbindResult struct {
	UnbindResult *UnbindResult `protobuf:"bytes,33,opt,name=unbind_result,json=unbindResult,proto3,oneof"`
}

type Frame_DomainSync struct {
	DomainSync *DomainSync `protobuf:"bytes,34,opt,name=domain_sync,json=domainSync,proto3,oneof"`
}

type Frame_DomainRevoked struct {
	DomainRevoked *DomainRevoked `protobuf:"bytes,35,opt,name=domain_revoked,json=domainRevoked,proto3,oneof"`
}

type Frame_DomainVerificationUpdate struct {
	DomainVerificationUpdate *DomainVerificationUpdate `protobuf:"bytes,36,opt,name=domain_verification_update,json=domainVerificationUpdate,proto3,oneof"`
}

func (*Frame_StreamData) isFrame_Body() {}

func (*Frame_StreamOpen) isFrame_Body() {}

func (*Frame_StreamClose) isFrame_Body() {}

func (*Frame_StreamReset) isFrame_Body() {}

func (*Frame_StreamOpenResult) isFrame_Body() {}

func (*Frame_Hello) isFrame_Body() {}

func (*Frame_Welcome) isFrame_Body() {}

func (*Frame_Ping) isFrame_Body() {}

func (*Frame_Pong) isFrame_Body() {}

func (*Frame_Goaway) isFrame_Body() {}

func (*Frame_Error) isFrame_Body() {}

func (*Frame_BindRequest) isFrame_Body() {}

func (*Frame_BindResult) isFrame_Body() {}

func (*Frame_UnbindRequest) isFrame_Body() {}

func (*Frame_UnbindResult) isFrame_Body() {}

func (*Frame_DomainSync) isFrame_Body() {}

func (*Frame_DomainRevoked) isFrame_Body() {}

func (*Frame_DomainVerificationUpdate) isFrame_Body() {}

type Hello struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion              uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ClientVersion                string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	SupportedFeatures            []string               `protobuf:"bytes,3,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	MaxConcurrentStreams         uint32                 `protobuf:"varint,10,opt,name=max_concurrent_streams,json=maxConcurrentStreams,proto3" json:"max_concurrent_streams,omitempty"`
	MaxFrameSizeBytes            uint32                 `protobuf:"varint,11,opt,name=max_frame_size_bytes,json=maxFrameSizeBytes,proto3" json:"max_frame_size_bytes,omitempty"`
	PreferredPingIntervalSeconds uint32                 `protobuf:"varint,12,opt,name=preferred_ping_interval_seconds,json=preferredPingIntervalSeconds,proto3" json:"preferred_ping_interval_seconds,omitempty"`
	PreviousSessionId            string                 `protobuf:"bytes,20,opt,name=previous_session_id,json=previousSessionId,proto3" json:"previous_session_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *Hello) GetMaxConcurrentStreams() uint32 {
	if x != nil {
		return x.MaxConcurrentStreams
	}
	return 0
}

func (x *Hello) GetMaxFrameSizeBytes() uint32 {
	if x != nil {
		return x.MaxFrameSizeBytes
	}
	return 0
}

func (x *Hello) GetPreferredPingIntervalSeconds() uint32 {
	if x != nil {
		return x.PreferredPingIntervalSeconds
	}
	return 0
}

func (x *Hello) GetPreviousSessionId() string {
	if x != nil {
		return x.PreviousSessionId
	}
	return ""
}

type Welcome struct {
	state                   protoimpl.MessageState      `protogen:"open.v1"`
	SessionId               string                      `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerTimeUnixMs        int64                       `protobuf:"varint,2,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	AcceptedProtocolVersion uint32                      `protobuf:"varint,3,opt,name=accepted_protocol_version,json=acceptedProtocolVersion,proto3" json:"accepted_protocol_version,omitempty"`
	ServerFeatures          []string                    `protobuf:"bytes,4,rep,name=server_features,json=serverFeatures,proto3" json:"server_features,omitempty"`
	MaxConcurrentStreams    uint32                      `protobuf:"varint,10,opt,name=max_concurrent_streams,json=maxConcurrentStreams,proto3" json:"max_concurrent_streams,omitempty"`
	MaxFrameSizeBytes       uint32                      `protobuf:"varint,11,opt,name=max_frame_size_bytes,json=maxFrameSizeBytes,proto3" json:"max_frame_size_bytes,omitempty"`
	PingIntervalSeconds     uint32                      `protobuf:"varint,12,opt,name=ping_interval_seconds,json=pingIntervalSeconds,proto3" json:"ping_interval_seconds,omitempty"`
	AuthorizedDomains       []*DomainBinding            `protobuf:"bytes,20,rep,name=authorized_domains,json=authorizedDomains,proto3" json:"authorized_domains,omitempty"`
	DomainVerifications     []*DomainVerificationUpdate `protobuf:"bytes,21,rep,name=domain_verifications,json=domainVerifications,proto3" json:"domain_verifications,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_proto_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Welcome) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Welcome) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

func (x *Welcome) GetAcceptedProtocolVersion() uint32 {
	if x != nil {
		return x.AcceptedProtocolVersion
	}
	return 0
}

func (x *Welcome) GetServerFeatures() []string {
	if x != nil {
		return x.ServerFeatures
	}
	return nil
}

func (x *Welcome) GetMaxConcurrentStreams() uint32 {
	if x != nil {
		return x.MaxConcurrentStreams
	}
	return 0
}

func (x *Welcome) GetMaxFrameSizeBytes() uint32 {
	if x != nil {
		return x.MaxFrameSizeBytes
	}
	return 0
}

func (x *Welcome) GetPingIntervalSeconds() uint32 {
	if x != nil {
		return x.PingIntervalSeconds
	}
	return 0
}

func (x *Welcome) GetAuthorizedDomains() []*DomainBinding {
	if x != nil {
		return x.AuthorizedDomains
	}
	return nil
}

func (x *Welcome) GetDomainVerifications() []*DomainVerificationUpdate {
	if x != nil {
		return x.DomainVerifications
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opaque        []byte                 `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	SentAtUnixMs  uint64                 `protobuf:"varint,2,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetOpaque() []byte {
	if x != nil {
		return x.Opaque
	}
	return nil
}

func (x *Ping) GetSentAtUnixMs() uint64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

type Pong struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Opaque           []byte                 `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	PingSentAtUnixMs uint64                 `protobuf:"varint,2,opt,name=ping_sent_at_unix_ms,json=pingSentAtUnixMs,proto3" json:"ping_sent_at_unix_ms,omitempty"`
	SentAtUnixMs     uint64                 `protobuf:"varint,3,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetOpaque() []byte {
	if x != nil {
		return x.Opaque
	}
	return nil
}

func (x *Pong) GetPingSentAtUnixMs() uint64 {
	if x != nil {
		return x.PingSentAtUnixMs
	}
	return 0
}

func (x *Pong) GetSentAtUnixMs() uint64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

type GoAway struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              TunnelErrorCode        `protobuf:"varint,1,opt,name=code,proto3,enum=tunnel.v2.TunnelErrorCode" json:"code,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reconnect         bool                   `protobuf:"varint,3,opt,name=reconnect,proto3" json:"reconnect,omitempty"`
	RetryAfterSeconds uint32                 `protobuf:"varint,4,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	Reason            DisconnectReason       `protobuf:"varint,5,opt,name=reason,proto3,enum=tunnel.v2.DisconnectReason" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GoAway) Reset() {
	*x = GoAway{}
	mi := &file_proto_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoAway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoAway) ProtoMessage() {}

func (x *GoAway) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoAway.ProtoReflect.Descriptor instead.
func (*GoAway) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *GoAway) GetCode() TunnelErrorCode {
	if x != nil {
		return x.Code
	}
	return TunnelErrorCode_TUNNEL_ERROR_CODE_UNSPECIFIED
}

func (x *GoAway) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GoAway) GetReconnect() bool {
	if x != nil {
		return x.Reconnect
	}
	return false
}

func (x *GoAway) GetRetryAfterSeconds() uint32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

func (x *GoAway) GetReason() DisconnectReason {
	if x != nil {
		return x.Reason
	}
	return DisconnectReason_DISCONNECT_REASON_UNSPECIFIED
}

type TunnelError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          TunnelErrorCode        `protobuf:"varint,1,opt,name=code,proto3,enum=tunnel.v2.TunnelErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelError) Reset() {
	*x = TunnelError{}
	mi := &file_proto_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelError) ProtoMessage() {}

func (x *TunnelError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelError.ProtoReflect.Descriptor instead.
func (*TunnelError) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelError) GetCode() TunnelErrorCode {
	if x != nil {
		return x.Code
	}
	return TunnelErrorCode_TUNNEL_ERROR_CODE_UNSPECIFIED
}

func (x *TunnelError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TunnelError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type StreamOpen struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Domain         string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Sni            string                 `protobuf:"bytes,2,opt,name=sni,proto3" json:"sni,omitempty"`
	RemoteAddr     string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	OpenedAtUnixMs int64                  `protobuf:"varint,4,opt,name=opened_at_unix_ms,json=openedAtUnixMs,proto3" json:"opened_at_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamOpen) Reset() {
	*x = StreamOpen{}
	mi := &file_proto_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpen) ProtoMessage() {}

func (x *StreamOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpen.ProtoReflect.Descriptor instead.
func (*StreamOpen) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOpen) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *StreamOpen) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *StreamOpen) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *StreamOpen) GetOpenedAtUnixMs() int64 {
	if x != nil {
		return x.OpenedAtUnixMs
	}
	return 0
}

type StreamClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        CloseReason            `protobuf:"varint,1,opt,name=reason,proto3,enum=tunnel.v2.CloseReason" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamClose) Reset() {
	*x = StreamClose{}
	mi := &file_proto_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClose) ProtoMessage() {}

func (x *StreamClose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClose.ProtoReflect.Descriptor instead.
func (*StreamClose) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *StreamClose) GetReason() CloseReason {
	if x != nil {
		return x.Reason
	}
	return CloseReason_CLOSE_REASON_UNSPECIFIED
}

func (x *StreamClose) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          TunnelErrorCode        `protobuf:"varint,1,opt,name=code,proto3,enum=tunnel.v2.TunnelErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReset) Reset() {
	*x = StreamReset{}
	mi := &file_proto_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReset) ProtoMessage() {}

func (x *StreamReset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReset.ProtoReflect.Descriptor instead.
func (*StreamReset) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *StreamReset) GetCode() TunnelErrorCode {
	if x != nil {
		return x.Code
	}
	return TunnelErrorCode_TUNNEL_ERROR_CODE_UNSPECIFIED
}

func (x *StreamReset) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamOpenResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     TunnelErrorCode        `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=tunnel.v2.TunnelErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOpenResult) Reset() {
	*x = StreamOpenResult{}
	mi := &file_proto_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOpenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpenResult) ProtoMessage() {}

func (x *StreamOpenResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpenResult.ProtoReflect.Descriptor instead.
func (*StreamOpenResult) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *StreamOpenResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamOpenResult) GetErrorCode() TunnelErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return TunnelErrorCode_TUNNEL_ERROR_CODE_UNSPECIFIED
}

func (x *StreamOpenResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ServeMode     ServeMode              `protobuf:"varint,2,opt,name=serve_mode,json=serveMode,proto3,enum=tunnel.v2.ServeMode" json:"serve_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_proto_tunnel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{11}
}

func (x *BindRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BindRequest) GetServeMode() ServeMode {
	if x != nil {
		return x.ServeMode
	}
	return ServeMode_SERVE_MODE_UNSPECIFIED
}

type BindResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     TunnelErrorCode        `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=tunnel.v2.TunnelErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindResult) Reset() {
	*x = BindResult{}
	mi := &file_proto_tunnel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResult) ProtoMessage() {}

func (x *BindResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResult.ProtoReflect.Descriptor instead.
func (*BindResult) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{12}
}

func (x *BindResult) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BindResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindResult) GetErrorCode() TunnelErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return TunnelErrorCode_TUNNEL_ERROR_CODE_UNSPECIFIED
}

func (x *BindResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnbindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindRequest) Reset() {
	*x = UnbindRequest{}
	mi := &file_proto_tunnel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindRequest) ProtoMessage() {}

func (x *UnbindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindRequest.ProtoReflect.Descriptor instead.
func (*UnbindRequest) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *UnbindRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type UnbindResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     TunnelErrorCode        `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=tunnel.v2.TunnelErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindResult) Reset() {
	*x = UnbindResult{}
	mi := &file_proto_tunnel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindResult) ProtoMessage() {}

func (x *UnbindResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindResult.ProtoReflect.Descriptor instead.
func (*UnbindResult) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{14}
}

func (x *UnbindResult) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UnbindResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnbindResult) GetErrorCode() TunnelErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return TunnelErrorCode_TUNNEL_ERROR_CODE_UNSPECIFIED
}

func (x *UnbindResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DomainSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*DomainBinding       `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainSync) Reset() {
	*x = DomainSync{}
	mi := &file_proto_tunnel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainSync) ProtoMessage() {}

func (x *DomainSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainSync.ProtoReflect.Descriptor instead.
func (*DomainSync) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{15}
}

func (x *DomainSync) GetDomains() []*DomainBinding {
	if x != nil {
		return x.Domains
	}
	return nil
}

type DomainBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Status        DomainStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=tunnel.v2.DomainStatus" json:"status,omitempty"`
	Bound         bool                   `protobuf:"varint,3,opt,name=bound,proto3" json:"bound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainBinding) Reset() {
	*x = DomainBinding{}
	mi := &file_proto_tunnel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainBinding) ProtoMessage() {}

func (x *DomainBinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainBinding.ProtoReflect.Descriptor instead.
func (*DomainBinding) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{16}
}

func (x *DomainBinding) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainBinding) GetStatus() DomainStatus {
	if x != nil {
		return x.Status
	}
	return DomainStatus_DOMAIN_STATUS_UNSPECIFIED
}

func (x *DomainBinding) GetBound() bool {
	if x != nil {
		return x.Bound
	}
	return false
}

type DomainRevoked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RevokeReason  DomainRevokeReason     `protobuf:"varint,3,opt,name=revoke_reason,json=revokeReason,proto3,enum=tunnel.v2.DomainRevokeReason" json:"revoke_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainRevoked) Reset() {
	*x = DomainRevoked{}
	mi := &file_proto_tunnel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainRevoked) ProtoMessage() {}

func (x *DomainRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainRevoked.ProtoReflect.Descriptor instead.
func (*DomainRevoked) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{17}
}

func (x *DomainRevoked) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainRevoked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DomainRevoked) GetRevokeReason() DomainRevokeReason {
	if x != nil {
		return x.RevokeReason
	}
	return DomainRevokeReason_DOMAIN_REVOKE_REASON_UNSPECIFIED
}

type DomainVerificationUpdate struct {
	state                    protoimpl.MessageState   `protogen:"open.v1"`
	Domain                   string                   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Status                   DomainVerificationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=tunnel.v2.DomainVerificationStatus" json:"status,omitempty"`
	RecordName               string                   `protobuf:"bytes,3,opt,name=record_name,json=recordName,proto3" json:"record_name,omitempty"`
	RecordValue              string                   `protobuf:"bytes,4,opt,name=record_value,json=recordValue,proto3" json:"record_value,omitempty"`
	TtlSeconds               uint32                   `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ExpiresAtUnixMs          int64                    `protobuf:"varint,6,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	VerificationAttempts     uint32                   `protobuf:"varint,7,opt,name=verification_attempts,json=verificationAttempts,proto3" json:"verification_attempts,omitempty"`
	NextVerificationAtUnixMs int64                    `protobuf:"varint,8,opt,name=next_verification_at_unix_ms,json=nextVerificationAtUnixMs,proto3" json:"next_verification_at_unix_ms,omitempty"`
	LastVerificationAtUnixMs int64                    `protobuf:"varint,9,opt,name=last_verification_at_unix_ms,json=lastVerificationAtUnixMs,proto3" json:"last_verification_at_unix_ms,omitempty"`
	LastError                string                   `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	VerifiedAtUnixMs         int64                    `protobuf:"varint,11,opt,name=verified_at_unix_ms,json=verifiedAtUnixMs,proto3" json:"verified_at_unix_ms,omitempty"`
	CanRequestNewChallenge   bool                     `protobuf:"varint,12,opt,name=can_request_new_challenge,json=canRequestNewChallenge,proto3" json:"can_request_new_challenge,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DomainVerificationUpdate) Reset() {
	*x = DomainVerificationUpdate{}
	mi := &file_proto_tunnel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainVerificationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainVerificationUpdate) ProtoMessage() {}

func (x *DomainVerificationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainVerificationUpdate.ProtoReflect.Descriptor instead.
func (*DomainVerificationUpdate) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{18}
}

func (x *DomainVerificationUpdate) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainVerificationUpdate) GetStatus() DomainVerificationStatus {
	if x != nil {
		return x.Status
	}
	return DomainVerificationStatus_DOMAIN_VERIFICATION_STATUS_UNSPECIFIED
}

func (x *DomainVerificationUpdate) GetRecordName() string {
	if x != nil {
		return x.RecordName
	}
	return ""
}

func (x *DomainVerificationUpdate) GetRecordValue() string {
	if x != nil {
		return x.RecordValue
	}
	return ""
}

func (x *DomainVerificationUpdate) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *DomainVerificationUpdate) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *DomainVerificationUpdate) GetVerificationAttempts() uint32 {
	if x != nil {
		return x.VerificationAttempts
	}
	return 0
}

func (x *DomainVerificationUpdate) GetNextVerificationAtUnixMs() int64 {
	if x != nil {
		return x.NextVerificationAtUnixMs
	}
	return 0
}

func (x *DomainVerificationUpdate) GetLastVerificationAtUnixMs() int64 {
	if x != nil {
		return x.LastVerificationAtUnixMs
	}
	return 0
}

func (x *DomainVerificationUpdate) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *DomainVerificationUpdate) GetVerifiedAtUnixMs() int64 {
	if x != nil {
		return x.VerifiedAtUnixMs
	}
	return 0
}

func (x *DomainVerificationUpdate) GetCanRequestNewChallenge() bool {
	if x != nil {
		return x.CanRequestNewChallenge
	}
	return false
}

var File_proto_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tunnel.proto\x12\ttunnel.v2\"\xd0\b\n" +
	"\x05Frame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12!\n" +
	"\vstream_data\x18\n" +
	" \x01(\fH\x00R\n" +
	"streamData\x128\n" +
	"\vstream_open\x18\v \x01(\v2\x15.tunnel.v2.StreamOpenH\x00R\n" +
	"streamOpen\x12;\n" +
	"\fstream_close\x18\f \x01(\v2\x16.tunnel.v2.StreamCloseH\x00R\vstreamClose\x12;\n" +
	"\fstream_reset\x18\r \x01(\v2\x16.tunnel.v2.StreamResetH\x00R\vstreamReset\x12K\n" +
	"\x12stream_open_result\x18\x0e \x01(\v2\x1b.tunnel.v2.StreamOpenResultH\x00R\x10streamOpenResult\x12(\n" +
	"\x05hello\x18\x14 \x01(\v2\x10.tunnel.v2.HelloH\x00R\x05hello\x12.\n" +
	"\awelcome\x18\x15 \x01(\v2\x12.tunnel.v2.WelcomeH\x00R\awelcome\x12%\n" +
	"\x04ping\x18\x16 \x01(\v2\x0f.tunnel.v2.PingH\x00R\x04ping\x12%\n" +
	"\x04pong\x18\x17 \x01(\v2\x0f.tunnel.v2.PongH\x00R\x04pong\x12+\n" +
	"\x06goaway\x18\x18 \x01(\v2\x11.tunnel.v2.GoAwayH\x00R\x06goaway\x12.\n" +
	"\x05error\x18\x19 \x01(\v2\x16.tunnel.v2.TunnelErrorH\x00R\x05error\x12;\n" +
	"\fbind_request\x18\x1e \x01(\v2\x16.tunnel.v2.BindRequestH\x00R\vbindRequest\x128\n" +
	"\vbind_result\x18\x1f \x01(\v2\x15.tunnel.v2.BindResultH\x00R\n" +
	"bindResult\x12A\n" +
	"\x0eunbind_request\x18  \x01(\v2\x18.tunnel.v2.UnbindRequestH\x00R\runbindRequest\x12>\n" +
	"\runbind_result\x18! \x01(\v2\x17.tunnel.v2.UnbindResultH\x00R\funbindResult\x128\n" +
	"\vdomain_sync\x18\" \x01(\v2\x15.tunnel.v2.DomainSyncH\x00R\n" +
	"domainSync\x12A\n" +
	"\x0edomain_revoked\x18# \x01(\v2\x18.tunnel.v2.DomainRevokedH\x00R\rdomainRevoked\x12c\n" +
	"\x1adomain_verification_update\x18$ \x01(\v2#.tunnel.v2.DomainVerificationUpdateH\x00R\x18domainVerificationUpdateB\x06\n" +
	"\x04body\"\xe6\x02\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12-\n" +
	"\x12supported_features\x18\x03 \x03(\tR\x11supportedFeatures\x124\n" +
	"\x16max_concurrent_streams\x18\n" +
	" \x01(\rR\x14maxConcurrentStreams\x12/\n" +
	"\x14max_frame_size_bytes\x18\v \x01(\rR\x11maxFrameSizeBytes\x12E\n" +
	"\x1fpreferred_ping_interval_seconds\x18\f \x01(\rR\x1cpreferredPingIntervalSeconds\x12.\n" +
	"\x13previous_session_id\x18\x14 \x01(\tR\x11previousSessionId\"\xf8\x03\n" +
	"\aWelcome\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x13server_time_unix_ms\x18\x02 \x01(\x03R\x10serverTimeUnixMs\x12:\n" +
	"\x19accepted_protocol_version\x18\x03 \x01(\rR\x17acceptedProtocolVersion\x12'\n" +
	"\x0fserver_features\x18\x04 \x03(\tR\x0eserverFeatures\x124\n" +
	"\x16max_concurrent_streams\x18\n" +
	" \x01(\rR\x14maxConcurrentStreams\x12/\n" +
	"\x14max_frame_size_bytes\x18\v \x01(\rR\x11maxFrameSizeBytes\x122\n" +
	"\x15ping_interval_seconds\x18\f \x01(\rR\x13pingIntervalSeconds\x12G\n" +
	"\x12authorized_domains\x18\x14 \x03(\v2\x18.tunnel.v2.DomainBindingR\x11authorizedDomains\x12V\n" +
	"\x14domain_verifications\x18\x15 \x03(\v2#.tunnel.v2.DomainVerificationUpdateR\x13domainVerifications\"E\n" +
	"\x04Ping\x12\x16\n" +
	"\x06opaque\x18\x01 \x01(\fR\x06opaque\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x02 \x01(\x04R\fsentAtUnixMs\"u\n" +
	"\x04Pong\x12\x16\n" +
	"\x06opaque\x18\x01 \x01(\fR\x06opaque\x12.\n" +
	"\x14ping_sent_at_unix_ms\x18\x02 \x01(\x04R\x10pingSentAtUnixMs\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x03 \x01(\x04R\fsentAtUnixMs\"\xd5\x01\n" +
	"\x06GoAway\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.tunnel.v2.TunnelErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\treconnect\x18\x03 \x01(\bR\treconnect\x12.\n" +
	"\x13retry_after_seconds\x18\x04 \x01(\rR\x11retryAfterSeconds\x123\n" +
	"\x06reason\x18\x05 \x01(\x0e2\x1b.tunnel.v2.DisconnectReasonR\x06reason\"q\n" +
	"\vTunnelError\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.tunnel.v2.TunnelErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\x82\x01\n" +
	"\n" +
	"StreamOpen\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x10\n" +
	"\x03sni\x18\x02 \x01(\tR\x03sni\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12)\n" +
	"\x11opened_at_unix_ms\x18\x04 \x01(\x03R\x0eopenedAtUnixMs\"W\n" +
	"\vStreamClose\x12.\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x16.tunnel.v2.CloseReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\vStreamReset\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.tunnel.v2.TunnelErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x01\n" +
	"\x10StreamOpenResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x1a.tunnel.v2.TunnelErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Z\n" +
	"\vBindRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x123\n" +
	"\n" +
	"serve_mode\x18\x02 \x01(\x0e2\x14.tunnel.v2.ServeModeR\tserveMode\"\x93\x01\n" +
	"\n" +
	"BindResult\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x1a.tunnel.v2.TunnelErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"'\n" +
	"\rUnbindRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\x95\x01\n" +
	"\fUnbindResult\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x1a.tunnel.v2.TunnelErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"@\n" +
	"\n" +
	"DomainSync\x122\n" +
	"\adomains\x18\x01 \x03(\v2\x18.tunnel.v2.DomainBindingR\adomains\"\x88\x01\n" +
	"\rDomainBinding\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.tunnel.v2.DomainStatusR\x06status\x12\x14\n" +
	"\x05bound\x18\x03 \x01(\bR\x05boundJ\x04\b\x04\x10\x05R\x12relay_managed_zone\"\x83\x01\n" +
	"\rDomainRevoked\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12B\n" +
	"\rrevoke_reason\x18\x03 \x01(\x0e2\x1d.tunnel.v2.DomainRevokeReasonR\frevokeReason\"\xbf\x04\n" +
	"\x18DomainVerificationUpdate\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.tunnel.v2.DomainVerificationStatusR\x06status\x12\x1f\n" +
	"\vrecord_name\x18\x03 \x01(\tR\n" +
	"recordName\x12!\n" +
	"\frecord_value\x18\x04 \x01(\tR\vrecordValue\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\x12+\n" +
	"\x12expires_at_unix_ms\x18\x06 \x01(\x03R\x0fexpiresAtUnixMs\x123\n" +
	"\x15verification_attempts\x18\a \x01(\rR\x14verificationAttempts\x12>\n" +
	"\x1cnext_verification_at_unix_ms\x18\b \x01(\x03R\x18nextVerificationAtUnixMs\x12>\n" +
	"\x1clast_verification_at_unix_ms\x18\t \x01(\x03R\x18lastVerificationAtUnixMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\x12-\n" +
	"\x13verified_at_unix_ms\x18\v \x01(\x03R\x10verifiedAtUnixMs\x129\n" +
	"\x19can_request_new_challenge\x18\f \x01(\bR\x16canRequestNewChallenge*I\n" +
	"\tServeMode\x12\x1a\n" +
	"\x16SERVE_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSERVE_MODE_HTTPS_PASSTHROUGH\x10\x01*\xa1\x01\n" +
	"\fDomainStatus\x12\x1d\n" +
	"\x19DOMAIN_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DOMAIN_STATUS_PENDING_DNS\x10\x01\x12\x1c\n" +
	"\x18DOMAIN_STATUS_REGISTERED\x10\x02\x12\x1a\n" +
	"\x16DOMAIN_STATUS_DISABLED\x10\x03\x12\x19\n" +
	"\x15DOMAIN_STATUS_REVOKED\x10\x04*\xbf\x01\n" +
	"\x18DomainVerificationStatus\x12*\n" +
	"&DOMAIN_VERIFICATION_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"DOMAIN_VERIFICATION_STATUS_PENDING\x10\x01\x12'\n" +
	"#DOMAIN_VERIFICATION_STATUS_VERIFIED\x10\x02\x12&\n" +
	"\"DOMAIN_VERIFICATION_STATUS_EXPIRED\x10\x03*\xd9\x01\n" +
	"\vCloseReason\x12\x1c\n" +
	"\x18CLOSE_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CLOSE_REASON_NORMAL\x10\x01\x12\x1e\n" +
	"\x1aCLOSE_REASON_REMOTE_CLOSED\x10\x02\x12\x1d\n" +
	"\x19CLOSE_REASON_LOCAL_CLOSED\x10\x03\x12\x1d\n" +
	"\x19CLOSE_REASON_IDLE_TIMEOUT\x10\x04\x12\x1d\n" +
	"\x19CLOSE_REASON_POLICY_LIMIT\x10\x05\x12\x16\n" +
	"\x12CLOSE_REASON_ERROR\x10\x06*\xbf\x02\n" +
	"\x10DisconnectReason\x12!\n" +
	"\x1dDISCONNECT_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDISCONNECT_REASON_NETWORK_LOST\x10\x01\x12\"\n" +
	"\x1eDISCONNECT_REASON_AUTH_EXPIRED\x10\x02\x12$\n" +
	" DISCONNECT_REASON_SERVER_RESTART\x10\x03\x12'\n" +
	"#DISCONNECT_REASON_PROTOCOL_MISMATCH\x10\x04\x12$\n" +
	" DISCONNECT_REASON_DEVICE_REVOKED\x10\x05\x12'\n" +
	"#DISCONNECT_REASON_SERVER_OVERLOADED\x10\x06\x12\"\n" +
	"\x1eDISCONNECT_REASON_IDLE_TIMEOUT\x10\a*\xe5\x01\n" +
	"\x12DomainRevokeReason\x12$\n" +
	" DOMAIN_REVOKE_REASON_UNSPECIFIED\x10\x00\x12$\n" +
	" DOMAIN_REVOKE_REASON_DNS_INVALID\x10\x01\x12%\n" +
	"!DOMAIN_REVOKE_REASON_ADMIN_ACTION\x10\x02\x12,\n" +
	"(DOMAIN_REVOKE_REASON_DOMAIN_UNREGISTERED\x10\x04\"\x04\b\x03\x10\x03*(DOMAIN_REVOKE_REASON_CERTIFICATE_EXPIRED*\xf9\x04\n" +
	"\x0fTunnelErrorCode\x12!\n" +
	"\x1dTUNNEL_ERROR_CODE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fTUNNEL_ERROR_CODE_INVALID_FRAME\x10\x01\x122\n" +
	".TUNNEL_ERROR_CODE_PROTOCOL_VERSION_UNSUPPORTED\x10\x02\x12-\n" +
	")TUNNEL_ERROR_CODE_AUTHENTICATION_REQUIRED\x10\x03\x12$\n" +
	" TUNNEL_ERROR_CODE_DEVICE_REVOKED\x10\x04\x12$\n" +
	" TUNNEL_ERROR_CODE_INVALID_DOMAIN\x10\x05\x12+\n" +
	"'TUNNEL_ERROR_CODE_DOMAIN_NOT_REGISTERED\x10\x06\x12&\n" +
	"\"TUNNEL_ERROR_CODE_DOMAIN_NOT_OWNED\x10\a\x12%\n" +
	"!TUNNEL_ERROR_CODE_DOMAIN_DISABLED\x10\b\x12*\n" +
	"&TUNNEL_ERROR_CODE_DOMAIN_ALREADY_BOUND\x10\t\x12&\n" +
	"\"TUNNEL_ERROR_CODE_STREAM_NOT_FOUND\x10\n" +
	"\x12+\n" +
	"'TUNNEL_ERROR_CODE_STREAM_LIMIT_EXCEEDED\x10\v\x12%\n" +
	"!TUNNEL_ERROR_CODE_FRAME_TOO_LARGE\x10\f\x12+\n" +
	"'TUNNEL_ERROR_CODE_SERVER_UNDER_PRESSURE\x10\r\x12\x1e\n" +
	"\x1aTUNNEL_ERROR_CODE_INTERNAL\x10d2A\n" +
	"\rTunnelService\x120\n" +
	"\x06Tunnel\x12\x10.tunnel.v2.Frame\x1a\x10.tunnel.v2.Frame(\x010\x01BI\n" +
	"%com.projects.httpsserverapp.tunnel.v2P\x01Z\x1erelay/proto/tunnel/v2;tunnelpbb\x06proto3"

var (
	file_proto_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_proto_rawDescData
}

var file_proto_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_tunnel_proto_goTypes = []any{
	(ServeMode)(0),                   // 0: tunnel.v2.ServeMode
	(DomainStatus)(0),                // 1: tunnel.v2.DomainStatus
	(DomainVerificationStatus)(0),    // 2: tunnel.v2.DomainVerificationStatus
	(CloseReason)(0),                 // 3: tunnel.v2.CloseReason
	(DisconnectReason)(0),            // 4: tunnel.v2.DisconnectReason
	(DomainRevokeReason)(0),          // 5: tunnel.v2.DomainRevokeReason
	(TunnelErrorCode)(0),             // 6: tunnel.v2.TunnelErrorCode
	(*Frame)(nil),                    // 7: tunnel.v2.Frame
	(*Hello)(nil),                    // 8: tunnel.v2.Hello
	(*Welcome)(nil),                  // 9: tunnel.v2.Welcome
	(*Ping)(nil),                     // 10: tunnel.v2.Ping
	(*Pong)(nil),                     // 11: tunnel.v2.Pong
	(*GoAway)(nil),                   // 12: tunnel.v2.GoAway
	(*TunnelError)(nil),              // 13: tunnel.v2.TunnelError
	(*StreamOpen)(nil),               // 14: tunnel.v2.StreamOpen
	(*StreamClose)(nil),              // 15: tunnel.v2.StreamClose
	(*StreamReset)(nil),              // 16: tunnel.v2.StreamReset
	(*StreamOpenResult)(nil),         // 17: tunnel.v2.StreamOpenResult
	(*BindRequest)(nil),              // 18: tunnel.v2.BindRequest
	(*BindResult)(nil),               // 19: tunnel.v2.BindResult
	(*UnbindRequest)(nil),            // 20: tunnel.v2.UnbindRequest
	(*UnbindResult)(nil),             // 21: tunnel.v2.UnbindResult
	(*DomainSync)(nil),               // 22: tunnel.v2.DomainSync
	(*DomainBinding)(nil),            // 23: tunnel.v2.DomainBinding
	(*DomainRevoked)(nil),            // 24: tunnel.v2.DomainRevoked
	(*DomainVerificationUpdate)(nil), // 25: tunnel.v2.DomainVerificationUpdate
}
var file_proto_tunnel_proto_depIdxs = []int32{
	14, // 0: tunnel.v2.Frame.stream_open:type_name -> tunnel.v2.StreamOpen
	15, // 1: tunnel.v2.Frame.stream_close:type_name -> tunnel.v2.StreamClose
	16, // 2: tunnel.v2.Frame.stream_reset:type_name -> tunnel.v2.StreamReset
	17, // 3: tunnel.v2.Frame.stream_open_result:type_name -> tunnel.v2.StreamOpenResult
	8,  // 4: tunnel.v2.Frame.hello:type_name -> tunnel.v2.Hello
	9,  // 5: tunnel.v2.Frame.welcome:type_name -> tunnel.v2.Welcome
	10, // 6: tunnel.v2.Frame.ping:type_name -> tunnel.v2.Ping
	11, // 7: tunnel.v2.Frame.pong:type_name -> tunnel.v2.Pong
	12, // 8: tunnel.v2.Frame.goaway:type_name -> tunnel.v2.GoAway
	13, // 9: tunnel.v2.Frame.error:type_name -> tunnel.v2.TunnelError
	18, // 10: tunnel.v2.Frame.bind_request:type_name -> tunnel.v2.BindRequest
	19, // 11: tunnel.v2.Frame.bind_result:type_name -> tunnel.v2.BindResult
	20, // 12: tunnel.v2.Frame.unbind_request:type_name -> tunnel.v2.UnbindRequest
	21, // 13: tunnel.v2.Frame.unbind_result:type_name -> tunnel.v2.UnbindResult
	22, // 14: tunnel.v2.Frame.domain_sync:type_name -> tunnel.v2.DomainSync
	24, // 15: tunnel.v2.Frame.domain_revoked:type_name -> tunnel.v2.DomainRevoked
	25, // 16: tunnel.v2.Frame.domain_verification_update:type_name -> tunnel.v2.DomainVerificationUpdate
	23, // 17: tunnel.v2.Welcome.authorized_domains:type_name -> tunnel.v2.DomainBinding
	25, // 18: tunnel.v2.Welcome.domain_verifications:type_name -> tunnel.v2.DomainVerificationUpdate
	6,  // 19: tunnel.v2.GoAway.code:type_name -> tunnel.v2.TunnelErrorCode
	4,  // 20: tunnel.v2.GoAway.reason:type_name -> tunnel.v2.DisconnectReason
	6,  // 21: tunnel.v2.TunnelError.code:type_name -> tunnel.v2.TunnelErrorCode
	3,  // 22: tunnel.v2.StreamClose.reason:type_name -> tunnel.v2.CloseReason
	6,  // 23: tunnel.v2.StreamReset.code:type_name -> tunnel.v2.TunnelErrorCode
	6,  // 24: tunnel.v2.StreamOpenResult.error_code:type_name -> tunnel.v2.TunnelErrorCode
	0,  // 25: tunnel.v2.BindRequest.serve_mode:type_name -> tunnel.v2.ServeMode
	6,  // 26: tunnel.v2.BindResult.error_code:type_name -> tunnel.v2.TunnelErrorCode
	6,  // 27: tunnel.v2.UnbindResult.error_code:type_name -> tunnel.v2.TunnelErrorCode
	23, // 28: tunnel.v2.DomainSync.domains:type_name -> tunnel.v2.DomainBinding
	1,  // 29: tunnel.v2.DomainBinding.status:type_name -> tunnel.v2.DomainStatus
	5,  // 30: tunnel.v2.DomainRevoked.revoke_reason:type_name -> tunnel.v2.DomainRevokeReason
	2,  // 31: tunnel.v2.DomainVerificationUpdate.status:type_name -> tunnel.v2.DomainVerificationStatus
	7,  // 32: tunnel.v2.TunnelService.Tunnel:input_type -> tunnel.v2.Frame
	7,  // 33: tunnel.v2.TunnelService.Tunnel:output_type -> tunnel.v2.Frame
	33, // [33:34] is the sub-list for method output_type
	32, // [32:33] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_proto_tunnel_proto_init() }
func file_proto_tunnel_proto_init() {
	if File_proto_tunnel_proto != nil {
		return
	}
	file_proto_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_StreamData)(nil),
		(*Frame_StreamOpen)(nil),
		(*Frame_StreamClose)(nil),
		(*Frame_StreamReset)(nil),
		(*Frame_StreamOpenResult)(nil),
		(*Frame_Hello)(nil),
		(*Frame_Welcome)(nil),
		(*Frame_Ping)(nil),
		(*Frame_Pong)(nil),
		(*Frame_Goaway)(nil),
		(*Frame_Error)(nil),
		(*Frame_BindRequest)(nil),
		(*Frame_BindResult)(nil),
		(*Frame_UnbindRequest)(nil),
		(*Frame_UnbindResult)(nil),
		(*Frame_DomainSync)(nil),
		(*Frame_DomainRevoked)(nil),
		(*Frame_DomainVerificationUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_proto_depIdxs,
		EnumInfos:         file_proto_tunnel_proto_enumTypes,
		MessageInfos:      file_proto_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_proto = out.File
	file_proto_tunnel_proto_goTypes = nil
	file_proto_tunnel_proto_depIdxs = nil
}
